import type { Lang } from '../../i18n/core';

// Tuple order keeps all existing locales complete without silent English fallbacks.
const values: Record<Lang, string[]> = {
 en:['Browser task','Steps run in a separate browser window on this computer. Approve the plan in its Terminal. Close that window or press Ctrl+C to stop.','Open page','Read page','Click','Fill field','Scroll','Upload file','Download file','Add step','Remove step','Send browser task','Website URL','Element selector','Text','Pixels','File path','Queue these browser steps? Local approval is still required.','Could not queue this browser task. Refresh the computer status and try again.'],
 el:['Εργασία browser','Τα βήματα εκτελούνται σε ξεχωριστό παράθυρο στον υπολογιστή. Ενέκρινε το πλάνο στο Terminal του. Κλείσε το παράθυρο ή πάτησε Ctrl+C για διακοπή.','Άνοιγμα σελίδας','Ανάγνωση σελίδας','Κλικ','Συμπλήρωση πεδίου','Κύλιση','Ανέβασμα αρχείου','Λήψη αρχείου','Προσθήκη βήματος','Αφαίρεση βήματος','Αποστολή εργασίας browser','Διεύθυνση σελίδας','Επιλογέας στοιχείου','Κείμενο','Εικονοστοιχεία','Διαδρομή αρχείου','Να σταλούν αυτά τα βήματα; Χρειάζεται και τοπική έγκριση.','Η εργασία δεν στάλθηκε. Ανανέωσε την κατάσταση του υπολογιστή και δοκίμασε ξανά.'],
 es:['Tarea de navegador','Los pasos se ejecutan en una ventana separada de este ordenador. Aprueba el plan en su Terminal. Cierra la ventana o pulsa Ctrl+C para detenerlo.','Abrir página','Leer página','Clic','Rellenar campo','Desplazar','Subir archivo','Descargar archivo','Añadir paso','Quitar paso','Enviar tarea','URL del sitio','Selector del elemento','Texto','Píxeles','Ruta del archivo','¿Enviar estos pasos? También se requiere aprobación local.','No se pudo enviar. Actualiza el estado del ordenador e inténtalo de nuevo.'],
 'pt-BR':['Tarefa de navegador','As etapas usam uma janela separada neste computador. Aprove o plano no Terminal. Feche a janela ou pressione Ctrl+C para parar.','Abrir página','Ler página','Clicar','Preencher campo','Rolar','Enviar arquivo','Baixar arquivo','Adicionar etapa','Remover etapa','Enviar tarefa','URL do site','Seletor do elemento','Texto','Pixels','Caminho do arquivo','Enviar estas etapas? A aprovação local também é necessária.','Não foi possível enviar. Atualize o status do computador e tente novamente.'],
 fr:['Tâche de navigateur','Les étapes utilisent une fenêtre séparée sur cet ordinateur. Approuvez le plan dans son Terminal. Fermez la fenêtre ou appuyez sur Ctrl+C pour arrêter.','Ouvrir une page','Lire la page','Cliquer','Remplir un champ','Défiler','Importer un fichier','Télécharger un fichier','Ajouter une étape','Supprimer l’étape','Envoyer la tâche','URL du site','Sélecteur de l’élément','Texte','Pixels','Chemin du fichier','Envoyer ces étapes ? Une approbation locale reste nécessaire.','Envoi impossible. Actualisez l’état de l’ordinateur et réessayez.'],
 de:['Browseraufgabe','Die Schritte laufen in einem eigenen Fenster auf diesem Computer. Bestätige den Plan im Terminal. Schließe das Fenster oder drücke Ctrl+C zum Stoppen.','Seite öffnen','Seite lesen','Klicken','Feld ausfüllen','Scrollen','Datei hochladen','Datei herunterladen','Schritt hinzufügen','Schritt entfernen','Aufgabe senden','Website-URL','Elementselektor','Text','Pixel','Dateipfad','Diese Schritte senden? Lokale Zustimmung bleibt erforderlich.','Senden fehlgeschlagen. Aktualisiere den Computerstatus und versuche es erneut.'],
 'zh-CN':['浏览器任务','步骤在此计算机的独立窗口中运行。请在终端批准计划。关闭窗口或按 Ctrl+C 停止。','打开页面','读取页面','点击','填写字段','滚动','上传文件','下载文件','添加步骤','删除步骤','发送任务','网站 URL','元素选择器','文本','像素','文件路径','发送这些步骤？仍需要本地批准。','无法发送任务。请刷新计算机状态后重试。'],
 ar:['مهمة المتصفح','تعمل الخطوات في نافذة منفصلة على هذا الحاسوب. وافق على الخطة في الطرفية. أغلق النافذة أو اضغط Ctrl+C للإيقاف.','فتح صفحة','قراءة الصفحة','نقر','تعبئة حقل','تمرير','رفع ملف','تنزيل ملف','إضافة خطوة','حذف خطوة','إرسال المهمة','رابط الموقع','محدد العنصر','النص','بكسل','مسار الملف','إرسال هذه الخطوات؟ تبقى الموافقة المحلية مطلوبة.','تعذر الإرسال. حدّث حالة الحاسوب وحاول مجدداً.'],
};
export const browserTaskLabels = (language: Lang) => {
 const [title,note,open,read,click,fill,scroll,upload,download,add,remove,send,url,selector,text,pixels,path,confirm,error]=values[language];
 return {title,note,open,read,click,fill,scroll,upload,download,add,remove,send,url,selector,text,pixels,path,confirm,error};
};
