import type { Lang } from '../../i18n/core';
const en = {
  refresh: 'Refresh', devicesError: 'Computer status could not be refreshed. Actions are locked until a successful refresh.',
  jobsError: 'Job history could not be refreshed.', cancelQueued: 'Cancel queued job', stopRunning: 'Stop running job', stopRequested: 'Stop requested',
  cancelNotice: 'Queued work cancels immediately. Stop on running work is a request to the paired Connector; the final status changes only after the computer confirms interruption. Offline/network loss can delay it.',
  capabilityNote: 'This Connector handles permitted files, explicitly enabled commands and opening public HTTPS pages in the local browser. Browser click/type/scroll, screen and mouse control are not active here.',
  execWarning: 'Advanced: a shell command is NOT confined to the allowed folder. It runs with the local user’s permissions. Enable it only on a trusted, isolated test computer.',
  codeExpired: 'This displayed pairing code has expired. Request a new code for the unpaired computer.',
  copied: 'Copied', copyError: 'Copy failed. Select and copy the text manually.',
  history: 'Recent jobs', noJobs: 'No recent jobs for this computer.',
  clockNote: 'Online means a recent Connector heartbeat, not a guarantee of desktop-control permissions.',
};
type Labels = { [K in keyof typeof en]: string };
export const computerManagerLabels: Record<Lang, Labels> = {
 en,
 el: { refresh:'Ανανέωση', devicesError:'Δεν ανανεώθηκε η κατάσταση των υπολογιστών. Οι ενέργειες κλειδώνουν μέχρι να επιτύχει η ανανέωση.', jobsError:'Δεν ανανεώθηκε το ιστορικό εργασιών.', cancelQueued:'Ακύρωση εργασίας σε αναμονή', stopRunning:'Stop εκτελούμενης εργασίας', stopRequested:'Ζητήθηκε Stop', cancelNotice:'Η εργασία σε αναμονή ακυρώνεται αμέσως. Σε εκτελούμενη εργασία το Stop στέλνει αίτημα στον συνδεδεμένο Connector· η τελική κατάσταση αλλάζει μόνο όταν ο υπολογιστής επιβεβαιώσει τη διακοπή. Offline ή πρόβλημα δικτύου μπορεί να το καθυστερήσει.', capabilityNote:'Ο Connector χειρίζεται επιτρεπόμενα αρχεία, εντολές που ενεργοποιούνται ρητά και άνοιγμα δημόσιων HTTPS σελίδων στον τοπικό browser. Ο έλεγχος click/type/scroll, οθόνης και ποντικιού δεν είναι ενεργός εδώ.', execWarning:'Για προχωρημένους: η εντολή shell ΔΕΝ περιορίζεται στον επιτρεπόμενο φάκελο. Εκτελείται με τα δικαιώματα του τοπικού χρήστη. Ενεργοποίησέ την μόνο σε έμπιστο, απομονωμένο υπολογιστή δοκιμών.', codeExpired:'Ο εμφανιζόμενος κωδικός σύνδεσης έληξε. Ζήτησε νέο κωδικό για τον μη συνδεδεμένο υπολογιστή.', copied:'Αντιγράφηκε', copyError:'Η αντιγραφή απέτυχε. Επίλεξε και αντέγραψε το κείμενο χειροκίνητα.', history:'Πρόσφατες εργασίες', noJobs:'Δεν υπάρχουν πρόσφατες εργασίες για αυτόν τον υπολογιστή.', clockNote:'Online σημαίνει πρόσφατη επικοινωνία του Connector, όχι εγγύηση δικαιωμάτων ελέγχου υπολογιστή.' },
 es: { refresh:'Actualizar', devicesError:'No se pudo actualizar el estado. Las acciones se bloquean hasta una actualización correcta.', jobsError:'No se pudo actualizar el historial.', cancelQueued:'Cancelar tarea en cola', stopRunning:'Detener tarea en ejecución', stopRequested:'Detención solicitada', cancelNotice:'Las tareas en cola se cancelan de inmediato. Para una tarea en ejecución, Detener envía una solicitud al Connector vinculado; el estado final cambia solo cuando el equipo confirma la interrupción. La falta de conexión puede retrasarla.', capabilityNote:'Este Connector gestiona archivos permitidos, comandos habilitados expresamente y la apertura de páginas HTTPS públicas en el navegador local. El control click/type/scroll, de pantalla y de ratón no está activo aquí.', execWarning:'Avanzado: un comando de shell NO está limitado a la carpeta autorizada. Se ejecuta con los permisos del usuario local. Actívalo solo en un equipo de prueba fiable y aislado.', codeExpired:'El código mostrado ha caducado. Solicita otro para el equipo sin vincular.', copied:'Copiado', copyError:'No se pudo copiar. Selecciona y copia el texto manualmente.', history:'Tareas recientes', noJobs:'No hay tareas recientes para este equipo.', clockNote:'En línea indica una comunicación reciente del Connector, no garantiza permisos de control.' },
 'pt-BR': { refresh:'Atualizar', devicesError:'Não foi possível atualizar o status. As ações ficam bloqueadas até uma atualização bem-sucedida.', jobsError:'Não foi possível atualizar o histórico.', cancelQueued:'Cancelar tarefa na fila', stopRunning:'Parar tarefa em execução', stopRequested:'Parada solicitada', cancelNotice:'Tarefas na fila são canceladas imediatamente. Em uma tarefa em execução, Parar envia uma solicitação ao Connector pareado; o status final muda somente após o computador confirmar a interrupção. Falta de rede pode atrasar isso.', capabilityNote:'Este Connector gerencia arquivos permitidos, comandos habilitados explicitamente e a abertura de páginas HTTPS públicas no navegador local. O controle click/type/scroll, de tela e de mouse não está ativo aqui.', execWarning:'Avançado: comandos de shell NÃO ficam restritos à pasta permitida. Eles usam as permissões do usuário local. Habilite apenas em um computador de teste confiável e isolado.', codeExpired:'O código exibido expirou. Solicite outro para o computador não pareado.', copied:'Copiado', copyError:'Falha ao copiar. Selecione e copie o texto manualmente.', history:'Tarefas recentes', noJobs:'Nenhuma tarefa recente para este computador.', clockNote:'Online indica contato recente do Connector, não garante permissões de controle.' },
 fr: { refresh:'Actualiser', devicesError:'L’état des ordinateurs n’a pas pu être actualisé. Les actions restent verrouillées jusqu’à une actualisation réussie.', jobsError:'L’historique n’a pas pu être actualisé.', cancelQueued:'Annuler la tâche en attente', stopRunning:'Arrêter la tâche en cours', stopRequested:'Arrêt demandé', cancelNotice:'Une tâche en attente est annulée immédiatement. Pour une tâche en cours, Arrêter envoie une demande au Connector associé ; l’état final ne change qu’après confirmation de l’interruption par l’ordinateur. Une perte de réseau peut la retarder.', capabilityNote:'Ce Connector gère les fichiers autorisés, les commandes explicitement activées et l’ouverture de pages HTTPS publiques dans le navigateur local. Le contrôle click/type/scroll, de l’écran et de la souris n’est pas actif ici.', execWarning:'Avancé : une commande shell n’est PAS limitée au dossier autorisé. Elle utilise les droits de l’utilisateur local. Activez-la uniquement sur un ordinateur de test fiable et isolé.', codeExpired:'Le code affiché a expiré. Demandez-en un nouveau pour l’ordinateur non associé.', copied:'Copié', copyError:'Échec de la copie. Sélectionnez et copiez le texte manuellement.', history:'Tâches récentes', noJobs:'Aucune tâche récente pour cet ordinateur.', clockNote:'En ligne signifie un contact récent du Connector, sans garantie des droits de contrôle.' },
 de: { refresh:'Aktualisieren', devicesError:'Der Computerstatus konnte nicht aktualisiert werden. Aktionen bleiben bis zur erfolgreichen Aktualisierung gesperrt.', jobsError:'Der Verlauf konnte nicht aktualisiert werden.', cancelQueued:'Wartenden Auftrag abbrechen', stopRunning:'Laufenden Auftrag stoppen', stopRequested:'Stop angefordert', cancelNotice:'Wartende Aufträge werden sofort abgebrochen. Bei laufender Arbeit sendet Stop eine Anfrage an den gekoppelten Connector; der Endstatus ändert sich erst nach bestätigter Unterbrechung durch den Computer. Netzwerkverlust kann dies verzögern.', capabilityNote:'Dieser Connector verwaltet erlaubte Dateien, ausdrücklich aktivierte Befehle und das Öffnen öffentlicher HTTPS-Seiten im lokalen Browser. click/type/scroll-, Bildschirm- und Maussteuerung sind hier nicht aktiv.', execWarning:'Erweitert: Shell-Befehle sind NICHT auf den erlaubten Ordner beschränkt. Sie laufen mit den Rechten des lokalen Benutzers. Nur auf einem vertrauenswürdigen, isolierten Testcomputer aktivieren.', codeExpired:'Der angezeigte Kopplungscode ist abgelaufen. Fordere für den ungepaarten Computer einen neuen an.', copied:'Kopiert', copyError:'Kopieren fehlgeschlagen. Text manuell markieren und kopieren.', history:'Letzte Aufträge', noJobs:'Keine letzten Aufträge für diesen Computer.', clockNote:'Online bedeutet einen aktuellen Connector-Kontakt, nicht garantierte Steuerungsrechte.' },
 'zh-CN': { refresh:'刷新', devicesError:'无法刷新计算机状态。成功刷新之前，操作保持锁定。', jobsError:'无法刷新任务记录。', cancelQueued:'取消排队任务', stopRunning:'停止正在运行的任务', stopRequested:'已请求停止', cancelNotice:'排队任务会立即取消。对于正在运行的任务，“停止”会向已配对的 Connector 发送请求；只有计算机确认中断后最终状态才会改变。离线或网络中断可能导致延迟。', capabilityNote:'此 Connector 处理授权文件、明确启用的命令，以及在本地浏览器打开公共 HTTPS 页面。click/type/scroll、屏幕和鼠标控制尚未启用。', execWarning:'高级功能：Shell 命令不会被限制在授权文件夹中，而是以本地用户权限运行。仅在可信、隔离的测试计算机上启用。', codeExpired:'显示的配对码已过期。请为尚未配对的计算机申请新代码。', copied:'已复制', copyError:'复制失败。请手动选择并复制文本。', history:'近期任务', noJobs:'此计算机没有近期任务。', clockNote:'在线仅表示 Connector 最近有通信，不代表拥有桌面控制权限。' },
 ar: { refresh:'تحديث', devicesError:'تعذّر تحديث حالة الحواسيب. تبقى الإجراءات مقفلة حتى ينجح التحديث.', jobsError:'تعذّر تحديث سجل المهام.', cancelQueued:'إلغاء مهمة في الانتظار', stopRunning:'إيقاف المهمة الجارية', stopRequested:'تم طلب الإيقاف', cancelNotice:'تُلغى المهمة المنتظرة فوراً. للمهمة الجارية يرسل زر الإيقاف طلباً إلى Connector المقترن؛ ولا تتغير الحالة النهائية إلا بعد أن يؤكد الحاسوب المقاطعة. قد يؤخر انقطاع الشبكة ذلك.', capabilityNote:'يتعامل هذا Connector مع الملفات المسموحة والأوامر المفعّلة صراحةً وفتح صفحات HTTPS العامة في المتصفح المحلي. التحكم click/type/scroll والشاشة والفأرة غير مفعّل هنا.', execWarning:'متقدم: أمر shell غير محصور في المجلد المسموح. يعمل بصلاحيات المستخدم المحلي. فعّله فقط على حاسوب اختبار موثوق ومعزول.', codeExpired:'انتهت صلاحية رمز الاقتران المعروض. اطلب رمزاً جديداً للحاسوب غير المقترن.', copied:'تم النسخ', copyError:'فشل النسخ. حدد النص وانسخه يدوياً.', history:'المهام الأخيرة', noJobs:'لا توجد مهام حديثة لهذا الحاسوب.', clockNote:'متصل يعني تواصلاً حديثاً من Connector، وليس ضماناً لصلاحيات التحكم.' },
};
