import type { Lang } from '../../i18n/core';
const en = {
  refresh: 'Refresh', devicesError: 'Computer status could not be refreshed. Actions are locked until a successful refresh.',
  jobsError: 'Job history could not be refreshed.', cancelQueued: 'Cancel queued job',
  cancelNotice: 'Cancelling a queued job does not stop a command already running on the computer. Use the local Connector to stop it.',
  capabilityNote: 'This Connector handles permitted files and explicitly enabled commands. Visible browser, screen and mouse control require the upcoming Firbo Desktop executor; they are not active here.',
  execWarning: 'Advanced: a shell command is NOT confined to the allowed folder. It runs with the local user’s permissions. Enable it only on a trusted, isolated test computer.',
  codeExpired: 'This displayed pairing code has expired. Request a new code for the unpaired computer.',
  copied: 'Copied', copyError: 'Copy failed. Select and copy the text manually.',
  history: 'Recent jobs', noJobs: 'No recent jobs for this computer.',
  clockNote: 'Online means a recent Connector heartbeat, not a guarantee of desktop-control permissions.',
};
type Labels = { [K in keyof typeof en]: string };
export const computerManagerLabels: Record<Lang, Labels> = {
 en,
 el: { refresh:'Ανανέωση', devicesError:'Δεν ανανεώθηκε η κατάσταση των υπολογιστών. Οι ενέργειες κλειδώνουν μέχρι να επιτύχει η ανανέωση.', jobsError:'Δεν ανανεώθηκε το ιστορικό εργασιών.', cancelQueued:'Ακύρωση εργασίας σε αναμονή', cancelNotice:'Η ακύρωση εργασίας σε αναμονή δεν σταματά εντολή που ήδη εκτελείται. Χρησιμοποίησε τον τοπικό Connector για διακοπή.', capabilityNote:'Ο Connector χειρίζεται επιτρεπόμενα αρχεία και εντολές που ενεργοποιούνται ρητά. Ορατός browser, οθόνη και ποντίκι απαιτούν τον νέο εκτελεστή Firbo Desktop· δεν είναι ενεργά εδώ.', execWarning:'Για προχωρημένους: η εντολή shell ΔΕΝ περιορίζεται στον επιτρεπόμενο φάκελο. Εκτελείται με τα δικαιώματα του τοπικού χρήστη. Ενεργοποίησέ την μόνο σε έμπιστο, απομονωμένο υπολογιστή δοκιμών.', codeExpired:'Ο εμφανιζόμενος κωδικός σύνδεσης έληξε. Ζήτησε νέο κωδικό για τον μη συνδεδεμένο υπολογιστή.', copied:'Αντιγράφηκε', copyError:'Η αντιγραφή απέτυχε. Επίλεξε και αντέγραψε το κείμενο χειροκίνητα.', history:'Πρόσφατες εργασίες', noJobs:'Δεν υπάρχουν πρόσφατες εργασίες για αυτόν τον υπολογιστή.', clockNote:'Online σημαίνει πρόσφατη επικοινωνία του Connector, όχι εγγύηση δικαιωμάτων ελέγχου υπολογιστή.' },
 es: { refresh:'Actualizar', devicesError:'No se pudo actualizar el estado. Las acciones se bloquean hasta una actualización correcta.', jobsError:'No se pudo actualizar el historial.', cancelQueued:'Cancelar tarea en cola', cancelNotice:'Cancelar una tarea en cola no detiene un comando en ejecución. Utiliza el Connector local para detenerlo.', capabilityNote:'Este Connector gestiona archivos permitidos y comandos habilitados expresamente. El navegador visible, la pantalla y el ratón requieren el futuro ejecutor Firbo Desktop; no están activos aquí.', execWarning:'Avanzado: un comando de shell NO está limitado a la carpeta autorizada. Se ejecuta con los permisos del usuario local. Actívalo solo en un equipo de prueba fiable y aislado.', codeExpired:'El código mostrado ha caducado. Solicita otro para el equipo sin vincular.', copied:'Copiado', copyError:'No se pudo copiar. Selecciona y copia el texto manualmente.', history:'Tareas recientes', noJobs:'No hay tareas recientes para este equipo.', clockNote:'En línea indica una comunicación reciente del Connector, no garantiza permisos de control.' },
 'pt-BR': { refresh:'Atualizar', devicesError:'Não foi possível atualizar o status. As ações ficam bloqueadas até uma atualização bem-sucedida.', jobsError:'Não foi possível atualizar o histórico.', cancelQueued:'Cancelar tarefa na fila', cancelNotice:'Cancelar uma tarefa na fila não para um comando em execução. Use o Connector local para interrompê-lo.', capabilityNote:'Este Connector gerencia arquivos permitidos e comandos habilitados explicitamente. Navegador visível, tela e mouse precisam do futuro executor Firbo Desktop; não estão ativos aqui.', execWarning:'Avançado: comandos de shell NÃO ficam restritos à pasta permitida. Eles usam as permissões do usuário local. Habilite apenas em um computador de teste confiável e isolado.', codeExpired:'O código exibido expirou. Solicite outro para o computador não pareado.', copied:'Copiado', copyError:'Falha ao copiar. Selecione e copie o texto manualmente.', history:'Tarefas recentes', noJobs:'Nenhuma tarefa recente para este computador.', clockNote:'Online indica contato recente do Connector, não garante permissões de controle.' },
 fr: { refresh:'Actualiser', devicesError:'L’état des ordinateurs n’a pas pu être actualisé. Les actions restent verrouillées jusqu’à une actualisation réussie.', jobsError:'L’historique n’a pas pu être actualisé.', cancelQueued:'Annuler la tâche en attente', cancelNotice:'Annuler une tâche en attente n’arrête pas une commande en cours. Utilisez le Connector local pour l’arrêter.', capabilityNote:'Ce Connector gère les fichiers autorisés et les commandes explicitement activées. Le navigateur visible, l’écran et la souris nécessitent le futur exécuteur Firbo Desktop ; ils ne sont pas actifs ici.', execWarning:'Avancé : une commande shell n’est PAS limitée au dossier autorisé. Elle utilise les droits de l’utilisateur local. Activez-la uniquement sur un ordinateur de test fiable et isolé.', codeExpired:'Le code affiché a expiré. Demandez-en un nouveau pour l’ordinateur non associé.', copied:'Copié', copyError:'Échec de la copie. Sélectionnez et copiez le texte manuellement.', history:'Tâches récentes', noJobs:'Aucune tâche récente pour cet ordinateur.', clockNote:'En ligne signifie un contact récent du Connector, sans garantie des droits de contrôle.' },
 de: { refresh:'Aktualisieren', devicesError:'Der Computerstatus konnte nicht aktualisiert werden. Aktionen bleiben bis zur erfolgreichen Aktualisierung gesperrt.', jobsError:'Der Verlauf konnte nicht aktualisiert werden.', cancelQueued:'Wartenden Auftrag abbrechen', cancelNotice:'Ein Abbruch in der Warteschlange stoppt keinen bereits laufenden Befehl. Verwende dafür den lokalen Connector.', capabilityNote:'Dieser Connector verwaltet erlaubte Dateien und ausdrücklich aktivierte Befehle. Sichtbarer Browser, Bildschirm und Maus benötigen den künftigen Firbo-Desktop-Ausführer; sie sind hier nicht aktiv.', execWarning:'Erweitert: Shell-Befehle sind NICHT auf den erlaubten Ordner beschränkt. Sie laufen mit den Rechten des lokalen Benutzers. Nur auf einem vertrauenswürdigen, isolierten Testcomputer aktivieren.', codeExpired:'Der angezeigte Kopplungscode ist abgelaufen. Fordere für den ungepaarten Computer einen neuen an.', copied:'Kopiert', copyError:'Kopieren fehlgeschlagen. Text manuell markieren und kopieren.', history:'Letzte Aufträge', noJobs:'Keine letzten Aufträge für diesen Computer.', clockNote:'Online bedeutet einen aktuellen Connector-Kontakt, nicht garantierte Steuerungsrechte.' },
 'zh-CN': { refresh:'刷新', devicesError:'无法刷新计算机状态。成功刷新之前，操作保持锁定。', jobsError:'无法刷新任务记录。', cancelQueued:'取消排队任务', cancelNotice:'取消排队任务不会停止计算机上正在运行的命令。请使用本地 Connector 停止它。', capabilityNote:'此 Connector 处理授权文件和明确启用的命令。可见浏览器、屏幕和鼠标控制需要后续的 Firbo Desktop 执行器；此处尚未启用。', execWarning:'高级功能：Shell 命令不会被限制在授权文件夹中，而是以本地用户权限运行。仅在可信、隔离的测试计算机上启用。', codeExpired:'显示的配对码已过期。请为尚未配对的计算机申请新代码。', copied:'已复制', copyError:'复制失败。请手动选择并复制文本。', history:'近期任务', noJobs:'此计算机没有近期任务。', clockNote:'在线仅表示 Connector 最近有通信，不代表拥有桌面控制权限。' },
 ar: { refresh:'تحديث', devicesError:'تعذّر تحديث حالة الحواسيب. تبقى الإجراءات مقفلة حتى ينجح التحديث.', jobsError:'تعذّر تحديث سجل المهام.', cancelQueued:'إلغاء مهمة في الانتظار', cancelNotice:'إلغاء مهمة في الانتظار لا يوقف أمراً يعمل على الحاسوب. استخدم Connector المحلي لإيقافه.', capabilityNote:'يتعامل هذا Connector مع الملفات المسموحة والأوامر المفعّلة صراحةً. المتصفح المرئي والشاشة والفأرة تحتاج إلى منفذ Firbo Desktop القادم؛ وهي غير مفعّلة هنا.', execWarning:'متقدم: أمر shell غير محصور في المجلد المسموح. يعمل بصلاحيات المستخدم المحلي. فعّله فقط على حاسوب اختبار موثوق ومعزول.', codeExpired:'انتهت صلاحية رمز الاقتران المعروض. اطلب رمزاً جديداً للحاسوب غير المقترن.', copied:'تم النسخ', copyError:'فشل النسخ. حدد النص وانسخه يدوياً.', history:'المهام الأخيرة', noJobs:'لا توجد مهام حديثة لهذا الحاسوب.', clockNote:'متصل يعني تواصلاً حديثاً من Connector، وليس ضماناً لصلاحيات التحكم.' },
};
