import type { Lang } from '../../i18n/core';

const en = {
  remove: 'Remove task', cancel: 'Cancel task', removing: 'Removing…', cancelling: 'Cancelling…', keep: 'Keep task',
  removeAsk: 'Permanently remove this task and its report? Related approval history is also removed. Execution receipts and the removal audit stay in Activity. This cannot be undone.',
  cancelAsk: 'Cancel this task and reject its pending approvals? No new execution will be started for it. You can then remove it separately.',
  removed: 'Task removed', cancelled: 'Task cancelled', cancelFirst: 'Cancel this task before removing it.',
  inProgress: 'Execution is running. Wait for it to finish before changing or removing the task. Changing a status cannot stop a running command.',
  changed: 'The task changed or is no longer accessible. Refresh and try again.', dependents: 'This task has child tasks. Finish or remove them first.',
  forbidden: 'Your current company role does not allow this action.', unavailable: 'Task management is not available on this backend yet.', failed: 'The task could not be changed. Try again.',
};
type Labels = { [K in keyof typeof en]: string };
const baseTaskActionLabels: Record<Lang, Labels> = {
  en,
  el: { remove:'Διαγραφή εργασίας', cancel:'Ακύρωση εργασίας', removing:'Διαγράφεται…', cancelling:'Ακυρώνεται…', keep:'Διατήρηση εργασίας', removeAsk:'Να διαγραφεί οριστικά αυτή η εργασία και η αναφορά της; Διαγράφεται επίσης το σχετικό ιστορικό εγκρίσεων. Οι αποδείξεις εκτέλεσης και ο έλεγχος διαγραφής παραμένουν στη Δραστηριότητα. Δεν γίνεται αναίρεση.', cancelAsk:'Να ακυρωθεί η εργασία και να απορριφθούν οι εκκρεμείς εγκρίσεις της; Δεν θα ξεκινήσει νέα εκτέλεση για αυτή. Μετά μπορείς να τη διαγράψεις χωριστά.', removed:'Η εργασία διαγράφηκε', cancelled:'Η εργασία ακυρώθηκε', cancelFirst:'Ακύρωσε την εργασία πριν τη διαγράψεις.', inProgress:'Η εκτέλεση βρίσκεται σε εξέλιξη. Περίμενε να τελειώσει πριν αλλάξεις ή διαγράψεις την εργασία. Η αλλαγή κατάστασης δεν σταματά εντολή που εκτελείται.', changed:'Η εργασία άλλαξε ή δεν είναι πλέον προσβάσιμη. Κάνε ανανέωση και δοκίμασε ξανά.', dependents:'Η εργασία έχει υποεργασίες. Ολοκλήρωσε ή διέγραψέ τες πρώτα.', forbidden:'Ο τρέχων ρόλος σου στην εταιρεία δεν επιτρέπει αυτή την ενέργεια.', unavailable:'Η διαχείριση εργασιών δεν είναι ακόμη διαθέσιμη σε αυτόν τον διακομιστή.', failed:'Δεν άλλαξε η εργασία. Δοκίμασε ξανά.' },
  es: { remove:'Eliminar tarea', cancel:'Cancelar tarea', removing:'Eliminando…', cancelling:'Cancelando…', keep:'Conservar tarea', removeAsk:'¿Eliminar definitivamente esta tarea y su informe? También se elimina su historial de aprobaciones. Los recibos de ejecución y la auditoría de eliminación permanecen en Actividad. No se puede deshacer.', cancelAsk:'¿Cancelar esta tarea y rechazar sus aprobaciones pendientes? No se iniciará una nueva ejecución. Después puedes eliminarla por separado.', removed:'Tarea eliminada', cancelled:'Tarea cancelada', cancelFirst:'Cancela la tarea antes de eliminarla.', inProgress:'Hay una ejecución en curso. Espera a que termine antes de cambiar o eliminar la tarea. Cambiar el estado no detiene un comando en ejecución.', changed:'La tarea cambió o ya no está disponible. Actualiza e inténtalo de nuevo.', dependents:'La tarea tiene subtareas. Complétalas o elimínalas primero.', forbidden:'Tu rol actual en la empresa no permite esta acción.', unavailable:'La gestión de tareas aún no está disponible en este servidor.', failed:'No se pudo cambiar la tarea. Inténtalo de nuevo.' },
  'pt-BR': { remove:'Remover tarefa', cancel:'Cancelar tarefa', removing:'Removendo…', cancelling:'Cancelando…', keep:'Manter tarefa', removeAsk:'Remover permanentemente esta tarefa e seu relatório? O histórico de aprovações também é removido. Os comprovantes de execução e a auditoria de remoção ficam em Atividade. Não é possível desfazer.', cancelAsk:'Cancelar esta tarefa e rejeitar suas aprovações pendentes? Nenhuma nova execução será iniciada. Depois você pode removê-la separadamente.', removed:'Tarefa removida', cancelled:'Tarefa cancelada', cancelFirst:'Cancele a tarefa antes de removê-la.', inProgress:'Há uma execução em andamento. Aguarde o término antes de alterar ou remover a tarefa. Alterar o status não interrompe um comando em execução.', changed:'A tarefa mudou ou não está mais acessível. Atualize e tente novamente.', dependents:'Esta tarefa tem subtarefas. Conclua ou remova-as primeiro.', forbidden:'Seu cargo atual na empresa não permite esta ação.', unavailable:'A gestão de tarefas ainda não está disponível neste servidor.', failed:'Não foi possível alterar a tarefa. Tente novamente.' },
  fr: { remove:'Supprimer la tâche', cancel:'Annuler la tâche', removing:'Suppression…', cancelling:'Annulation…', keep:'Conserver la tâche', removeAsk:'Supprimer définitivement cette tâche et son rapport ? Son historique d’approbations est également supprimé. Les reçus d’exécution et l’audit de suppression restent dans Activité. Cette action est irréversible.', cancelAsk:'Annuler cette tâche et rejeter ses approbations en attente ? Aucune nouvelle exécution ne sera lancée. Vous pourrez ensuite la supprimer séparément.', removed:'Tâche supprimée', cancelled:'Tâche annulée', cancelFirst:'Annulez la tâche avant de la supprimer.', inProgress:'Une exécution est en cours. Attendez sa fin avant de modifier ou supprimer la tâche. Changer le statut n’arrête pas une commande en cours.', changed:'La tâche a changé ou n’est plus accessible. Actualisez et réessayez.', dependents:'Cette tâche comporte des sous-tâches. Terminez-les ou supprimez-les d’abord.', forbidden:'Votre rôle actuel dans l’entreprise ne permet pas cette action.', unavailable:'La gestion des tâches n’est pas encore disponible sur ce serveur.', failed:'La tâche n’a pas pu être modifiée. Réessayez.' },
  de: { remove:'Aufgabe entfernen', cancel:'Aufgabe abbrechen', removing:'Wird entfernt…', cancelling:'Wird abgebrochen…', keep:'Aufgabe behalten', removeAsk:'Diese Aufgabe und ihren Bericht dauerhaft entfernen? Auch der Genehmigungsverlauf wird gelöscht. Ausführungsbelege und das Löschprotokoll bleiben unter Aktivität. Dies kann nicht rückgängig gemacht werden.', cancelAsk:'Diese Aufgabe abbrechen und ausstehende Genehmigungen ablehnen? Es wird keine neue Ausführung gestartet. Anschließend kannst du sie separat entfernen.', removed:'Aufgabe entfernt', cancelled:'Aufgabe abgebrochen', cancelFirst:'Brich die Aufgabe ab, bevor du sie entfernst.', inProgress:'Eine Ausführung läuft. Warte auf deren Ende, bevor du die Aufgabe änderst oder entfernst. Eine Statusänderung stoppt keinen laufenden Befehl.', changed:'Die Aufgabe wurde geändert oder ist nicht mehr zugänglich. Aktualisiere und versuche es erneut.', dependents:'Diese Aufgabe hat Unteraufgaben. Schließe sie zuerst ab oder entferne sie.', forbidden:'Deine aktuelle Firmenrolle erlaubt diese Aktion nicht.', unavailable:'Die Aufgabenverwaltung ist auf diesem Server noch nicht verfügbar.', failed:'Die Aufgabe konnte nicht geändert werden. Versuche es erneut.' },
  ar: { remove:'حذف المهمة', cancel:'إلغاء المهمة', removing:'جارٍ الحذف…', cancelling:'جارٍ الإلغاء…', keep:'الاحتفاظ بالمهمة', removeAsk:'هل تريد حذف هذه المهمة وتقريرها نهائيًا؟ يُحذف سجل الموافقات المرتبط أيضًا. تبقى إيصالات التنفيذ وسجل الحذف في النشاط. لا يمكن التراجع.', cancelAsk:'هل تريد إلغاء هذه المهمة ورفض موافقاتها المعلقة؟ لن يبدأ تنفيذ جديد لها. يمكنك حذفها بشكل منفصل لاحقًا.', removed:'تم حذف المهمة', cancelled:'تم إلغاء المهمة', cancelFirst:'ألغِ المهمة قبل حذفها.', inProgress:'هناك تنفيذ قيد التشغيل. انتظر انتهاءه قبل تغيير المهمة أو حذفها. تغيير الحالة لا يوقف أمرًا قيد التشغيل.', changed:'تغيرت المهمة أو لم تعد متاحة. حدّث الصفحة وحاول مجددًا.', dependents:'لهذه المهمة مهام فرعية. أكملها أو احذفها أولًا.', forbidden:'دورك الحالي في الشركة لا يسمح بهذا الإجراء.', unavailable:'إدارة المهام غير متاحة على هذا الخادم بعد.', failed:'تعذّر تغيير المهمة. حاول مجددًا.' },
  'zh-CN': { remove:'删除任务', cancel:'取消任务', removing:'正在删除…', cancelling:'正在取消…', keep:'保留任务', removeAsk:'永久删除此任务及其报告吗？相关审批记录也会被删除。执行回执和删除审计保留在活动中。此操作无法撤销。', cancelAsk:'取消此任务并拒绝其待处理审批吗？不会为此任务启动新的执行。之后可以单独删除它。', removed:'任务已删除', cancelled:'任务已取消', cancelFirst:'请先取消任务，再将其删除。', inProgress:'执行正在运行。请等待执行结束后再更改或删除任务。更改状态无法停止正在运行的命令。', changed:'任务已更改或无法访问。请刷新后重试。', dependents:'此任务包含子任务。请先完成或删除子任务。', forbidden:'你在公司的当前角色不允许此操作。', unavailable:'此服务器尚未提供任务管理功能。', failed:'无法更改任务。请重试。' },
};

type RecoveryLabels = { recover: string; recoverAsk: string; recovering: string; recovered: string; removalCancellation: string; notStalled: string };
const recoveryLabels: Record<Lang, RecoveryLabels> = {
  en: { recover:'Recover stalled task', recoverAsk:'Recover only if the task started and last changed over 30 minutes ago, with no active computer jobs, workflow, pending approvals or child tasks. The task becomes blocked and requires reconciliation. Existing results are preserved; this does not verify successful work or stop a running command.', recovering:'Recovering…', recovered:'Stalled task blocked for reconciliation', removalCancellation:'Pending approvals are rejected and queued computer jobs are cancelled before removal.', notStalled:'This task cannot be recovered yet: it must be inactive for over 30 minutes, with no active jobs, workflow, pending approvals or child tasks.' },
  el: { recover:'Ανάκτηση κολλημένης εργασίας', recoverAsk:'Ανάκτηση μόνο αν έχουν περάσει πάνω από 30 λεπτά από την έναρξη και την τελευταία αλλαγή, χωρίς ενεργές εργασίες υπολογιστή, ροή εργασιών, εκκρεμείς εγκρίσεις ή υποεργασίες. Η εργασία μπλοκάρεται και απαιτεί συμφιλίωση. Τα αποτελέσματα διατηρούνται· δεν επαληθεύεται επιτυχία και δεν σταματά εντολή που εκτελείται.', recovering:'Ανακτάται…', recovered:'Η κολλημένη εργασία μπλοκαρίστηκε για συμφιλίωση', removalCancellation:'Οι εκκρεμείς εγκρίσεις απορρίπτονται και οι εργασίες υπολογιστή σε αναμονή ακυρώνονται πριν τη διαγραφή.', notStalled:'Δεν επιτρέπεται ακόμη η ανάκτηση: χρειάζονται πάνω από 30 λεπτά αδράνειας, χωρίς ενεργές εργασίες, ροή εργασιών, εκκρεμείς εγκρίσεις ή υποεργασίες.' },
  es: { recover:'Recuperar tarea atascada', recoverAsk:'Solo se recupera si han pasado más de 30 minutos desde el inicio y el último cambio, sin trabajos activos, flujo de trabajo, aprobaciones pendientes ni subtareas. La tarea queda bloqueada y requiere conciliación. Se conservan los resultados; no se verifica el éxito ni se detiene un comando en ejecución.', recovering:'Recuperando…', recovered:'Tarea bloqueada para conciliación', removalCancellation:'Las aprobaciones pendientes se rechazan y los trabajos en cola se cancelan antes de eliminar.', notStalled:'Aún no se puede recuperar: necesita más de 30 minutos de inactividad y ningún trabajo activo, flujo de trabajo, aprobación pendiente o subtarea.' },
  'pt-BR': { recover:'Recuperar tarefa travada', recoverAsk:'A recuperação exige mais de 30 minutos desde o início e a última alteração, sem trabalhos ativos, fluxo de trabalho, aprovações pendentes ou subtarefas. A tarefa fica bloqueada para conciliação. Os resultados são preservados; isso não confirma o sucesso nem interrompe um comando em execução.', recovering:'Recuperando…', recovered:'Tarefa bloqueada para conciliação', removalCancellation:'Aprovações pendentes são rejeitadas e trabalhos na fila são cancelados antes da remoção.', notStalled:'Ainda não pode ser recuperada: exige mais de 30 minutos de inatividade, sem trabalhos ativos, fluxo de trabalho, aprovações pendentes ou subtarefas.' },
  fr: { recover:'Récupérer la tâche bloquée', recoverAsk:'La récupération exige plus de 30 minutes depuis le début et la dernière modification, sans travail actif, workflow, approbation en attente ni sous-tâche. La tâche est bloquée pour rapprochement. Les résultats sont conservés ; cela ne confirme pas la réussite et n’arrête pas une commande en cours.', recovering:'Récupération…', recovered:'Tâche bloquée pour rapprochement', removalCancellation:'Les approbations en attente sont rejetées et les travaux en file sont annulés avant la suppression.', notStalled:'La récupération exige plus de 30 minutes d’inactivité, sans travail actif, workflow, approbation en attente ni sous-tâche.' },
  de: { recover:'Festgefahrene Aufgabe wiederherstellen', recoverAsk:'Nur möglich, wenn Beginn und letzte Änderung über 30 Minuten zurückliegen und keine aktiven Computeraufträge, Workflows, offenen Genehmigungen oder Unteraufgaben bestehen. Die Aufgabe wird zur Abstimmung blockiert. Ergebnisse bleiben erhalten; dies bestätigt keinen Erfolg und stoppt keinen laufenden Befehl.', recovering:'Wiederherstellung…', recovered:'Aufgabe zur Abstimmung blockiert', removalCancellation:'Offene Genehmigungen werden abgelehnt und wartende Computeraufträge vor dem Entfernen abgebrochen.', notStalled:'Die Wiederherstellung verlangt über 30 Minuten Inaktivität ohne aktive Aufträge, Workflows, offene Genehmigungen oder Unteraufgaben.' },
  ar: { recover:'استعادة مهمة عالقة', recoverAsk:'تتطلب الاستعادة مرور أكثر من 30 دقيقة منذ البداية وآخر تعديل، دون مهام حاسوب نشطة أو سير عمل أو موافقات معلقة أو مهام فرعية. تصبح المهمة محظورة وتتطلب تسوية. تبقى النتائج محفوظة؛ لا يؤكد ذلك نجاح العمل ولا يوقف أمرًا قيد التشغيل.', recovering:'جارٍ الاستعادة…', recovered:'تم حظر المهمة للتسوية', removalCancellation:'تُرفض الموافقات المعلقة وتُلغى مهام الحاسوب في الانتظار قبل الحذف.', notStalled:'تتطلب الاستعادة أكثر من 30 دقيقة من عدم النشاط، دون مهام نشطة أو سير عمل أو موافقات معلقة أو مهام فرعية.' },
  'zh-CN': { recover:'恢复停滞任务', recoverAsk:'仅在任务启动和上次更改均已超过 30 分钟，且没有活动计算机作业、工作流、待处理审批或子任务时恢复。任务会被阻止并要求核对。现有结果保留；此操作不验证工作成功，也不会停止正在运行的命令。', recovering:'正在恢复…', recovered:'停滞任务已阻止，等待核对', removalCancellation:'删除前会拒绝待处理审批并取消排队的计算机作业。', notStalled:'尚不能恢复：需要超过 30 分钟无活动，且没有活动作业、工作流、待处理审批或子任务。' },
};
const reconciliationLabels: Record<Lang,string> = {
  en:'This task requires reconciliation before it can run again.', el:'Αυτή η εργασία απαιτεί συμφιλίωση πριν εκτελεστεί ξανά.', es:'Esta tarea requiere conciliación antes de volver a ejecutarse.', 'pt-BR':'Esta tarefa exige conciliação antes de executar novamente.', fr:'Cette tâche exige un rapprochement avant toute nouvelle exécution.', de:'Diese Aufgabe muss vor einer erneuten Ausführung abgestimmt werden.', ar:'تتطلب هذه المهمة تسوية قبل تشغيلها مجددًا.', 'zh-CN':'此任务需要核对后才能再次运行。',
};
export const taskActionLabels = Object.fromEntries(
  Object.entries(baseTaskActionLabels).map(([lang, labels]) => {
    const recovery = recoveryLabels[lang as Lang];
    return [lang, { ...labels, ...recovery, reconciliation: reconciliationLabels[lang as Lang], removeAsk: `${labels.removeAsk} ${recovery.removalCancellation}` }];
  }),
) as Record<Lang, Labels & RecoveryLabels & { reconciliation: string }>;
