// UI diagnostics, not model instructions. No recordings or server error bodies.
const en = { opening:'Opening the microphone…', listening:'Microphone on. Speak now.', transcribing:'Transcribing your voice…', preparing:'Preparing the voice reply…', speaking:'Speaking', browserListening:'Listening with browser speech recognition…', browserVoice:'Using the browser voice; audio level is unavailable.', noSpeech:'No speech detected. Check your microphone or use text.', server:'Voice service unavailable. Try again or use text.', playback:'Audio could not play. Your answer remains available as text.', stopped:'Voice stopped.', permission:'Microphone permission was not granted. Use text or allow access in your browser.', unsupported:'Microphone recording is not supported here. Use text.', thinking:'Preparing the answer…' };
type Messages = { [K in keyof typeof en]: string };
const messages: Record<string, Messages> = {
 en,
 el:{opening:'Άνοιγμα μικροφώνου…',listening:'Το μικρόφωνο είναι ενεργό. Μίλησε τώρα.',transcribing:'Μετατροπή της φωνής σε κείμενο…',preparing:'Προετοιμασία φωνητικής απάντησης…',speaking:'Μιλάει',browserListening:'Ακρόαση με την αναγνώριση φωνής του browser…',browserVoice:'Χρησιμοποιείται η φωνή του browser· δεν διατίθεται μέτρηση έντασης.',noSpeech:'Δεν εντοπίστηκε ομιλία. Έλεγξε το μικρόφωνο ή χρησιμοποίησε κείμενο.',server:'Η υπηρεσία φωνής δεν είναι διαθέσιμη. Δοκίμασε ξανά ή γράψε.',playback:'Ο ήχος δεν αναπαράχθηκε. Η απάντηση παραμένει διαθέσιμη ως κείμενο.',stopped:'Η φωνή σταμάτησε.',permission:'Δεν δόθηκε άδεια μικροφώνου. Γράψε ή επίτρεψε την πρόσβαση στον browser.',unsupported:'Δεν υποστηρίζεται καταγραφή μικροφώνου εδώ. Χρησιμοποίησε κείμενο.',thinking:'Προετοιμασία απάντησης…'},
 es:{opening:'Abriendo el micrófono…',listening:'Micrófono activo. Habla ahora.',transcribing:'Transcribiendo tu voz…',preparing:'Preparando la respuesta de voz…',speaking:'Hablando',browserListening:'Escuchando con el reconocimiento del navegador…',browserVoice:'Se usa la voz del navegador; no hay medición de nivel.',noSpeech:'No se detectó voz. Revisa el micrófono o escribe.',server:'El servicio de voz no está disponible. Reintenta o escribe.',playback:'No se pudo reproducir el audio. La respuesta sigue disponible como texto.',stopped:'Voz detenida.',permission:'No se concedió permiso al micrófono. Escribe o permite el acceso en el navegador.',unsupported:'No se admite la grabación aquí. Usa texto.',thinking:'Preparando la respuesta…'},
 'pt-BR':{opening:'Abrindo o microfone…',listening:'Microfone ativo. Fale agora.',transcribing:'Transcrevendo sua voz…',preparing:'Preparando a resposta de voz…',speaking:'Falando',browserListening:'Ouvindo com o reconhecimento do navegador…',browserVoice:'Usando a voz do navegador; o nível de áudio não está disponível.',noSpeech:'Nenhuma fala detectada. Verifique o microfone ou digite.',server:'Serviço de voz indisponível. Tente novamente ou digite.',playback:'O áudio não pôde ser reproduzido. A resposta continua disponível em texto.',stopped:'Voz interrompida.',permission:'Permissão de microfone não concedida. Digite ou permita o acesso no navegador.',unsupported:'Gravação não compatível aqui. Use texto.',thinking:'Preparando a resposta…'},
 fr:{opening:'Ouverture du microphone…',listening:'Microphone actif. Parlez maintenant.',transcribing:'Transcription de votre voix…',preparing:'Préparation de la réponse vocale…',speaking:'Parle',browserListening:'Écoute avec la reconnaissance du navigateur…',browserVoice:'Voix du navigateur utilisée ; le niveau sonore est indisponible.',noSpeech:'Aucune parole détectée. Vérifiez le microphone ou écrivez.',server:'Service vocal indisponible. Réessayez ou écrivez.',playback:'Lecture audio impossible. La réponse reste disponible en texte.',stopped:'Voix arrêtée.',permission:'Autorisation du microphone refusée. Écrivez ou autorisez l’accès dans le navigateur.',unsupported:'Enregistrement non pris en charge ici. Utilisez le texte.',thinking:'Préparation de la réponse…'},
 de:{opening:'Mikrofon wird geöffnet…',listening:'Mikrofon aktiv. Sprich jetzt.',transcribing:'Sprache wird transkribiert…',preparing:'Sprachantwort wird vorbereitet…',speaking:'Spricht',browserListening:'Zuhören mit der Spracherkennung des Browsers…',browserVoice:'Browserstimme aktiv; kein Audiopegel verfügbar.',noSpeech:'Keine Sprache erkannt. Prüfe das Mikrofon oder schreibe.',server:'Sprachdienst nicht verfügbar. Erneut versuchen oder schreiben.',playback:'Audio konnte nicht abgespielt werden. Die Antwort bleibt als Text verfügbar.',stopped:'Sprachausgabe gestoppt.',permission:'Mikrofonzugriff nicht erlaubt. Schreibe oder erlaube den Zugriff im Browser.',unsupported:'Aufnahme wird hier nicht unterstützt. Nutze Text.',thinking:'Antwort wird vorbereitet…'},
 'zh-CN':{opening:'正在打开麦克风…',listening:'麦克风已开启，请讲话。',transcribing:'正在转录语音…',preparing:'正在准备语音回复…',speaking:'正在讲话',browserListening:'正在使用浏览器语音识别…',browserVoice:'正在使用浏览器语音，无法测量音量。',noSpeech:'未检测到语音，请检查麦克风或输入文字。',server:'语音服务不可用，请重试或输入文字。',playback:'无法播放音频，回复仍可通过文字查看。',stopped:'语音已停止。',permission:'未授予麦克风权限，请输入文字或在浏览器中允许访问。',unsupported:'此环境不支持录音，请输入文字。',thinking:'正在准备回复…'},
 ar:{opening:'جارٍ فتح الميكروفون…',listening:'الميكروفون يعمل. تحدث الآن.',transcribing:'جارٍ تحويل الصوت إلى نص…',preparing:'جارٍ إعداد الرد الصوتي…',speaking:'يتحدث',browserListening:'استماع باستخدام التعرف الصوتي للمتصفح…',browserVoice:'يُستخدم صوت المتصفح؛ قياس مستوى الصوت غير متاح.',noSpeech:'لم يُكتشف كلام. تحقق من الميكروفون أو اكتب.',server:'خدمة الصوت غير متاحة. حاول مجددًا أو اكتب.',playback:'تعذر تشغيل الصوت. يبقى الرد متاحًا كنص.',stopped:'توقف الصوت.',permission:'لم يُمنح إذن الميكروفون. اكتب أو اسمح بالوصول من المتصفح.',unsupported:'التسجيل غير مدعوم هنا. استخدم النص.',thinking:'جارٍ إعداد الرد…'},
};
export const voiceMessages = (lang: string): Messages => messages[lang] ?? en;
export const voiceMessageLocales = messages;
