// Text for the Knowledge, Skills and Workflows pages, report feedback and two-way chat channels, in the 8 app languages.
// Kept next to the pages (like the Inbox's inline copy) so the shared locale files stay small.
import { useI18n } from '../../i18n/I18nProvider';

const en = {
  kEyebrow: 'Knowledge', kTitle: 'Company knowledge',
  kSub: 'Documents, links and apps your AI team reads before it answers. Only your company can see them.',
  kAddText: 'Add a note or document', kName: 'Name', kText: 'Paste the text: prices, policies, product details, FAQs…',
  kFile: 'or upload a file (.txt, .md, .csv, .json)', kAddUrl: 'Add a web page', kApp: 'Read a connected app',
  kAppNone: 'Connect Notion, GitHub, Google Drive, Gmail, Google Calendar or Outlook in Integrations first.',
  kAdd: 'Add', kSources: 'Sources', kEmpty: 'Nothing added yet.', kSync: 'Sync again', kDelete: 'Remove', kItems: '{n} passages',
  kSearch: 'Try a question', kSearchPh: 'Ask something your documents answer', kNoHits: 'Nothing found.', kSaved: 'Added. Your AI team can use it now.',
  kErr: 'That did not work. Try again.', kLimit: 'Your plan’s limit for knowledge sources is reached.', kBadUrl: 'Give a full https:// link.',
  kTooShort: 'The text is too short.', kManagersOnly: 'Only owners, admins and managers can add or remove knowledge.',
  sEyebrow: 'Skills', sTitle: 'Skills library',
  sSub: 'Ways of working your AI employees follow when a task matches. Install one for the whole team or for one employee.',
  sLibrary: 'Library', sInstalled: 'Installed', sInstall: 'Install', sFor: 'For', sTeam: 'Whole team', sCustom: 'Write your own skill',
  sInstr: 'The steps the employee should follow', sOn: 'On', sOff: 'Off', sRemove: 'Remove', sEmpty: 'No skills installed yet.', sDone: 'Installed.',
  wEyebrow: 'Workflows', wTitle: 'Workflows',
  wSub: 'A chain of steps, each done by an AI employee; every step gets the previous result. It runs on the server, even with the app closed.',
  wNew: 'New workflow', wEdit: 'Edit', wName: 'Name', wDesc: 'What it is for (optional)', wSteps: 'Steps', wAddStep: 'Add a step',
  wStepPh: 'What this employee should do with the input', wAgent: 'Employee', wTrigger: 'Starts', wManual: 'By hand', wSchedule: 'On a schedule',
  wWebhook: 'From another app (webhook)', wHourly: 'Every hour', wDaily: 'Every day', wWeekly: 'Every week', wAt: 'at', wSave: 'Save', wCancel: 'Cancel',
  wRun: 'Run now', wInput: 'Input for the first step (optional)', wRuns: 'Recent runs', wHook: 'Create webhook link',
  wHookShown: 'Copy this link now: it is shown only once. Anyone with it can start the workflow.', wDelete: 'Delete', wActive: 'Active',
  wEmpty: 'No workflows yet.', wStarted: 'Started. Follow the steps in Tasks.', wStep: 'Step {n}', wNoSteps: 'Add at least one step with an employee.',
  wNext: 'Next run', wRunning: 'running', wCompleted: 'done', wFailed: 'failed', wSaved: 'Saved.',
  fGood: 'Good report', fBad: 'Not good', fNote: 'What should be better? (optional)', fSend: 'Send', fThanks: 'Thanks. The employee learns from this.',
  cTitle: 'Two-way chat with your CEO', cOn: 'Turn on', cOff: 'Turn off', cIsOn: 'On',
  cHelp: 'Messages you send here go to your CEO, who answers in the same chat. Approvals arrive with Approve / Reject buttons.',
  cAppSecret: 'App secret (Meta app settings)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'In your Meta app, set this callback URL and verify token for WhatsApp webhooks.',
  aAsk: 'Ask {name}', aFound: 'What it found',
  dSlide: 'Slide {n} of {total}', dPptx: 'Download PowerPoint', dPrev: 'Previous slide', dNext: 'Next slide', dNotes: 'Speaker notes', dPolished: 'Reviewed for quality',
  xTitle: 'AI employees on this computer', xHelp: 'Let your AI team use this computer in tasks and shifts. Reading files, opening pages and the apps below happen at once; riskier steps wait for your approval in the Inbox; passwords, banking and system settings are never allowed.', xOn: 'AI employees may use this computer', xApps: 'Apps they open without asking (comma separated)', xShortcuts: 'Shortcuts they run without asking (comma separated)', xWrites: 'New files in the allowed folders', xCommands: 'Terminal commands', xAuto: 'Without asking', xAsk: 'Ask me first', xNever: 'Never', xSafe: 'Safe read-only ones without asking, the rest ask me', xHours: 'Only during these hours', xFrom: 'from', xTo: 'to', xSave: 'Save rules', xSaved: 'Saved.', xLocal: 'On the computer, also allow it once in the Connector, then restart it:', xByAi: 'AI', xKindApp: 'Open app', xKindShortcut: 'Shortcut', xPower: 'Then give an employee the power “Use the company computer” in Agent Studio.',
};
type Copy = typeof en;

const el: Copy = {
  kEyebrow: 'Γνώση', kTitle: 'Γνώση εταιρείας',
  kSub: 'Έγγραφα, σύνδεσμοι και εφαρμογές που διαβάζει η ομάδα AI πριν απαντήσει. Τα βλέπει μόνο η εταιρεία σας.',
  kAddText: 'Προσθήκη σημείωσης ή εγγράφου', kName: 'Όνομα', kText: 'Επικολλήστε το κείμενο: τιμές, πολιτικές, προϊόντα, συχνές ερωτήσεις…',
  kFile: 'ή ανεβάστε αρχείο (.txt, .md, .csv, .json)', kAddUrl: 'Προσθήκη ιστοσελίδας', kApp: 'Ανάγνωση συνδεδεμένης εφαρμογής',
  kAppNone: 'Συνδέστε πρώτα Notion, GitHub, Google Drive, Gmail, Google Calendar ή Outlook στις Ενσωματώσεις.',
  kAdd: 'Προσθήκη', kSources: 'Πηγές', kEmpty: 'Δεν έχει προστεθεί τίποτα ακόμα.', kSync: 'Συγχρονισμός', kDelete: 'Αφαίρεση', kItems: '{n} αποσπάσματα',
  kSearch: 'Δοκιμάστε μια ερώτηση', kSearchPh: 'Ρωτήστε κάτι που απαντούν τα έγγραφά σας', kNoHits: 'Δεν βρέθηκε τίποτα.', kSaved: 'Προστέθηκε. Η ομάδα AI μπορεί να το χρησιμοποιήσει.',
  kErr: 'Δεν έγινε. Δοκιμάστε ξανά.', kLimit: 'Συμπληρώθηκε το όριο πηγών γνώσης του πακέτου σας.', kBadUrl: 'Δώστε πλήρη σύνδεσμο https://.',
  kTooShort: 'Το κείμενο είναι πολύ μικρό.', kManagersOnly: 'Μόνο ιδιοκτήτες, διαχειριστές και managers προσθέτουν ή αφαιρούν γνώση.',
  sEyebrow: 'Δεξιότητες', sTitle: 'Βιβλιοθήκη δεξιοτήτων',
  sSub: 'Τρόποι δουλειάς που ακολουθούν οι AI υπάλληλοι όταν ταιριάζει η εργασία. Εγκαταστήστε για όλη την ομάδα ή για έναν υπάλληλο.',
  sLibrary: 'Βιβλιοθήκη', sInstalled: 'Εγκατεστημένες', sInstall: 'Εγκατάσταση', sFor: 'Για', sTeam: 'Όλη η ομάδα', sCustom: 'Γράψτε δική σας δεξιότητα',
  sInstr: 'Τα βήματα που ακολουθεί ο υπάλληλος', sOn: 'Ενεργή', sOff: 'Ανενεργή', sRemove: 'Αφαίρεση', sEmpty: 'Δεν υπάρχουν δεξιότητες ακόμα.', sDone: 'Εγκαταστάθηκε.',
  wEyebrow: 'Ροές εργασίας', wTitle: 'Ροές εργασίας',
  wSub: 'Αλυσίδα βημάτων, το καθένα από έναν AI υπάλληλο· κάθε βήμα παίρνει το αποτέλεσμα του προηγούμενου. Τρέχει στον server, ακόμα και με την εφαρμογή κλειστή.',
  wNew: 'Νέα ροή', wEdit: 'Επεξεργασία', wName: 'Όνομα', wDesc: 'Σκοπός (προαιρετικό)', wSteps: 'Βήματα', wAddStep: 'Προσθήκη βήματος',
  wStepPh: 'Τι κάνει αυτός ο υπάλληλος με την είσοδο', wAgent: 'Υπάλληλος', wTrigger: 'Ξεκινά', wManual: 'Χειροκίνητα', wSchedule: 'Με πρόγραμμα',
  wWebhook: 'Από άλλη εφαρμογή (webhook)', wHourly: 'Κάθε ώρα', wDaily: 'Κάθε μέρα', wWeekly: 'Κάθε εβδομάδα', wAt: 'στις', wSave: 'Αποθήκευση', wCancel: 'Άκυρο',
  wRun: 'Εκτέλεση τώρα', wInput: 'Είσοδος για το πρώτο βήμα (προαιρετικό)', wRuns: 'Πρόσφατες εκτελέσεις', wHook: 'Δημιουργία συνδέσμου webhook',
  wHookShown: 'Αντιγράψτε τον σύνδεσμο τώρα: εμφανίζεται μόνο μία φορά. Όποιος τον έχει μπορεί να ξεκινήσει τη ροή.', wDelete: 'Διαγραφή', wActive: 'Ενεργή',
  wEmpty: 'Δεν υπάρχουν ροές ακόμα.', wStarted: 'Ξεκίνησε. Δείτε τα βήματα στις Εργασίες.', wStep: 'Βήμα {n}', wNoSteps: 'Προσθέστε τουλάχιστον ένα βήμα με υπάλληλο.',
  wNext: 'Επόμενη εκτέλεση', wRunning: 'σε εξέλιξη', wCompleted: 'ολοκληρώθηκε', wFailed: 'απέτυχε', wSaved: 'Αποθηκεύτηκε.',
  fGood: 'Καλή αναφορά', fBad: 'Όχι καλή', fNote: 'Τι να βελτιωθεί; (προαιρετικό)', fSend: 'Αποστολή', fThanks: 'Ευχαριστούμε. Ο υπάλληλος μαθαίνει από αυτό.',
  cTitle: 'Συνομιλία διπλής κατεύθυνσης με τον CEO', cOn: 'Ενεργοποίηση', cOff: 'Απενεργοποίηση', cIsOn: 'Ενεργή',
  cHelp: 'Ό,τι γράφετε εδώ πηγαίνει στον CEO σας, που απαντά στην ίδια συνομιλία. Οι εγκρίσεις έρχονται με κουμπιά Έγκριση / Απόρριψη.',
  cAppSecret: 'App secret (ρυθμίσεις εφαρμογής Meta)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'Στην εφαρμογή Meta, βάλτε αυτό το callback URL και verify token για τα webhooks του WhatsApp.',
  aAsk: 'Ρώτησε: {name}', aFound: 'Τι βρήκε',
  dSlide: 'Διαφάνεια {n} από {total}', dPptx: 'Λήψη PowerPoint', dPrev: 'Προηγούμενη διαφάνεια', dNext: 'Επόμενη διαφάνεια', dNotes: 'Σημειώσεις ομιλητή', dPolished: 'Ελέγχθηκε για ποιότητα',
  xTitle: 'AI υπάλληλοι σε αυτόν τον υπολογιστή', xHelp: 'Η ομάδα AI μπορεί να χρησιμοποιεί αυτόν τον υπολογιστή σε εργασίες και βάρδιες. Ανάγνωση αρχείων, άνοιγμα σελίδων και οι παρακάτω εφαρμογές γίνονται αμέσως· τα πιο ριψοκίνδυνα περιμένουν την έγκρισή σου στα Εισερχόμενα· κωδικοί, τράπεζες και ρυθμίσεις συστήματος δεν επιτρέπονται ποτέ.', xOn: 'Οι AI υπάλληλοι μπορούν να χρησιμοποιούν αυτόν τον υπολογιστή', xApps: 'Εφαρμογές που ανοίγουν χωρίς να ρωτήσουν (με κόμμα)', xShortcuts: 'Shortcuts που τρέχουν χωρίς να ρωτήσουν (με κόμμα)', xWrites: 'Νέα αρχεία στους επιτρεπόμενους φακέλους', xCommands: 'Εντολές τερματικού', xAuto: 'Χωρίς ερώτηση', xAsk: 'Να με ρωτάνε', xNever: 'Ποτέ', xSafe: 'Οι ασφαλείς (μόνο ανάγνωση) χωρίς ερώτηση, οι άλλες να με ρωτάνε', xHours: 'Μόνο αυτές τις ώρες', xFrom: 'από', xTo: 'έως', xSave: 'Αποθήκευση κανόνων', xSaved: 'Αποθηκεύτηκε.', xLocal: 'Στον υπολογιστή, επίτρεψέ το και στο Connector μία φορά και μετά ξεκίνησέ το ξανά:', xByAi: 'AI', xKindApp: 'Άνοιγμα εφαρμογής', xKindShortcut: 'Shortcut', xPower: 'Μετά δώσε σε έναν υπάλληλο τη δύναμη «Χρήση του υπολογιστή της εταιρείας» στο Agent Studio.',
};

const es: Copy = {
  kEyebrow: 'Conocimiento', kTitle: 'Conocimiento de la empresa',
  kSub: 'Documentos, enlaces y apps que tu equipo de IA lee antes de responder. Solo tu empresa puede verlos.',
  kAddText: 'Añadir una nota o documento', kName: 'Nombre', kText: 'Pega el texto: precios, políticas, productos, preguntas frecuentes…',
  kFile: 'o sube un archivo (.txt, .md, .csv, .json)', kAddUrl: 'Añadir una página web', kApp: 'Leer una app conectada',
  kAppNone: 'Conecta primero Notion, GitHub, Google Drive, Gmail, Google Calendar u Outlook en Integraciones.',
  kAdd: 'Añadir', kSources: 'Fuentes', kEmpty: 'Aún no hay nada.', kSync: 'Sincronizar', kDelete: 'Quitar', kItems: '{n} fragmentos',
  kSearch: 'Prueba una pregunta', kSearchPh: 'Pregunta algo que respondan tus documentos', kNoHits: 'No se encontró nada.', kSaved: 'Añadido. Tu equipo de IA ya puede usarlo.',
  kErr: 'No funcionó. Inténtalo de nuevo.', kLimit: 'Has alcanzado el límite de fuentes de tu plan.', kBadUrl: 'Escribe un enlace https:// completo.',
  kTooShort: 'El texto es demasiado corto.', kManagersOnly: 'Solo propietarios, administradores y managers pueden añadir o quitar conocimiento.',
  sEyebrow: 'Habilidades', sTitle: 'Biblioteca de habilidades',
  sSub: 'Formas de trabajar que tus empleados de IA siguen cuando la tarea encaja. Instala una para todo el equipo o para un empleado.',
  sLibrary: 'Biblioteca', sInstalled: 'Instaladas', sInstall: 'Instalar', sFor: 'Para', sTeam: 'Todo el equipo', sCustom: 'Escribe tu propia habilidad',
  sInstr: 'Los pasos que debe seguir el empleado', sOn: 'Activa', sOff: 'Inactiva', sRemove: 'Quitar', sEmpty: 'Aún no hay habilidades.', sDone: 'Instalada.',
  wEyebrow: 'Flujos de trabajo', wTitle: 'Flujos de trabajo',
  wSub: 'Una cadena de pasos, cada uno hecho por un empleado de IA; cada paso recibe el resultado anterior. Se ejecuta en el servidor, incluso con la app cerrada.',
  wNew: 'Nuevo flujo', wEdit: 'Editar', wName: 'Nombre', wDesc: 'Para qué sirve (opcional)', wSteps: 'Pasos', wAddStep: 'Añadir paso',
  wStepPh: 'Qué debe hacer este empleado con la entrada', wAgent: 'Empleado', wTrigger: 'Empieza', wManual: 'A mano', wSchedule: 'Con horario',
  wWebhook: 'Desde otra app (webhook)', wHourly: 'Cada hora', wDaily: 'Cada día', wWeekly: 'Cada semana', wAt: 'a las', wSave: 'Guardar', wCancel: 'Cancelar',
  wRun: 'Ejecutar ahora', wInput: 'Entrada para el primer paso (opcional)', wRuns: 'Ejecuciones recientes', wHook: 'Crear enlace webhook',
  wHookShown: 'Copia el enlace ahora: solo se muestra una vez. Quien lo tenga puede iniciar el flujo.', wDelete: 'Eliminar', wActive: 'Activo',
  wEmpty: 'Aún no hay flujos.', wStarted: 'Iniciado. Sigue los pasos en Tareas.', wStep: 'Paso {n}', wNoSteps: 'Añade al menos un paso con un empleado.',
  wNext: 'Próxima ejecución', wRunning: 'en curso', wCompleted: 'terminado', wFailed: 'falló', wSaved: 'Guardado.',
  fGood: 'Buen informe', fBad: 'No es bueno', fNote: '¿Qué debería mejorar? (opcional)', fSend: 'Enviar', fThanks: 'Gracias. El empleado aprende de esto.',
  cTitle: 'Chat bidireccional con tu CEO', cOn: 'Activar', cOff: 'Desactivar', cIsOn: 'Activo',
  cHelp: 'Lo que escribas aquí llega a tu CEO, que responde en el mismo chat. Las aprobaciones llegan con botones Aprobar / Rechazar.',
  cAppSecret: 'App secret (ajustes de la app de Meta)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'En tu app de Meta, configura esta callback URL y el verify token para los webhooks de WhatsApp.',
  aAsk: 'Preguntar a {name}', aFound: 'Qué encontró',
  dSlide: 'Diapositiva {n} de {total}', dPptx: 'Descargar PowerPoint', dPrev: 'Diapositiva anterior', dNext: 'Diapositiva siguiente', dNotes: 'Notas del orador', dPolished: 'Revisado por calidad',
  xTitle: 'Empleados IA en este ordenador', xHelp: 'Tu equipo de IA puede usar este ordenador en tareas y turnos. Leer archivos, abrir páginas y las apps de abajo ocurre al momento; los pasos más arriesgados esperan tu aprobación en la Bandeja; contraseñas, bancos y ajustes del sistema nunca se permiten.', xOn: 'Los empleados IA pueden usar este ordenador', xApps: 'Apps que abren sin preguntar (separadas por comas)', xShortcuts: 'Atajos que ejecutan sin preguntar (separados por comas)', xWrites: 'Archivos nuevos en las carpetas permitidas', xCommands: 'Comandos de terminal', xAuto: 'Sin preguntar', xAsk: 'Preguntarme antes', xNever: 'Nunca', xSafe: 'Los seguros de solo lectura sin preguntar, el resto me pregunta', xHours: 'Solo en este horario', xFrom: 'de', xTo: 'a', xSave: 'Guardar reglas', xSaved: 'Guardado.', xLocal: 'En el ordenador, permítelo también una vez en el Connector y reinícialo:', xByAi: 'IA', xKindApp: 'Abrir app', xKindShortcut: 'Atajo', xPower: 'Luego da a un empleado el poder «Usar el ordenador de la empresa» en Agent Studio.',
};

const ptBR: Copy = {
  kEyebrow: 'Conhecimento', kTitle: 'Conhecimento da empresa',
  kSub: 'Documentos, links e apps que sua equipe de IA lê antes de responder. Só a sua empresa pode vê-los.',
  kAddText: 'Adicionar nota ou documento', kName: 'Nome', kText: 'Cole o texto: preços, políticas, produtos, perguntas frequentes…',
  kFile: 'ou envie um arquivo (.txt, .md, .csv, .json)', kAddUrl: 'Adicionar página web', kApp: 'Ler um app conectado',
  kAppNone: 'Conecte primeiro Notion, GitHub, Google Drive, Gmail, Google Calendar ou Outlook em Integrações.',
  kAdd: 'Adicionar', kSources: 'Fontes', kEmpty: 'Nada adicionado ainda.', kSync: 'Sincronizar', kDelete: 'Remover', kItems: '{n} trechos',
  kSearch: 'Teste uma pergunta', kSearchPh: 'Pergunte algo que seus documentos respondem', kNoHits: 'Nada encontrado.', kSaved: 'Adicionado. Sua equipe de IA já pode usar.',
  kErr: 'Não deu certo. Tente de novo.', kLimit: 'O limite de fontes do seu plano foi atingido.', kBadUrl: 'Informe um link https:// completo.',
  kTooShort: 'O texto é curto demais.', kManagersOnly: 'Só proprietários, administradores e gerentes podem adicionar ou remover conhecimento.',
  sEyebrow: 'Habilidades', sTitle: 'Biblioteca de habilidades',
  sSub: 'Formas de trabalhar que seus funcionários de IA seguem quando a tarefa combina. Instale para toda a equipe ou para um funcionário.',
  sLibrary: 'Biblioteca', sInstalled: 'Instaladas', sInstall: 'Instalar', sFor: 'Para', sTeam: 'Toda a equipe', sCustom: 'Escreva sua própria habilidade',
  sInstr: 'Os passos que o funcionário deve seguir', sOn: 'Ativa', sOff: 'Inativa', sRemove: 'Remover', sEmpty: 'Nenhuma habilidade ainda.', sDone: 'Instalada.',
  wEyebrow: 'Fluxos de trabalho', wTitle: 'Fluxos de trabalho',
  wSub: 'Uma cadeia de passos, cada um feito por um funcionário de IA; cada passo recebe o resultado anterior. Roda no servidor, mesmo com o app fechado.',
  wNew: 'Novo fluxo', wEdit: 'Editar', wName: 'Nome', wDesc: 'Para que serve (opcional)', wSteps: 'Passos', wAddStep: 'Adicionar passo',
  wStepPh: 'O que este funcionário deve fazer com a entrada', wAgent: 'Funcionário', wTrigger: 'Começa', wManual: 'Manualmente', wSchedule: 'Com agenda',
  wWebhook: 'De outro app (webhook)', wHourly: 'A cada hora', wDaily: 'Todo dia', wWeekly: 'Toda semana', wAt: 'às', wSave: 'Salvar', wCancel: 'Cancelar',
  wRun: 'Executar agora', wInput: 'Entrada para o primeiro passo (opcional)', wRuns: 'Execuções recentes', wHook: 'Criar link de webhook',
  wHookShown: 'Copie o link agora: ele aparece só uma vez. Quem tiver o link pode iniciar o fluxo.', wDelete: 'Excluir', wActive: 'Ativo',
  wEmpty: 'Nenhum fluxo ainda.', wStarted: 'Iniciado. Acompanhe os passos em Tarefas.', wStep: 'Passo {n}', wNoSteps: 'Adicione pelo menos um passo com um funcionário.',
  wNext: 'Próxima execução', wRunning: 'em andamento', wCompleted: 'concluído', wFailed: 'falhou', wSaved: 'Salvo.',
  fGood: 'Bom relatório', fBad: 'Não ficou bom', fNote: 'O que deve melhorar? (opcional)', fSend: 'Enviar', fThanks: 'Obrigado. O funcionário aprende com isso.',
  cTitle: 'Chat de mão dupla com seu CEO', cOn: 'Ativar', cOff: 'Desativar', cIsOn: 'Ativo',
  cHelp: 'O que você escreve aqui vai para o seu CEO, que responde na mesma conversa. Aprovações chegam com botões Aprovar / Rejeitar.',
  cAppSecret: 'App secret (configurações do app Meta)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'No seu app Meta, configure esta callback URL e o verify token para os webhooks do WhatsApp.',
  aAsk: 'Perguntar a {name}', aFound: 'O que encontrou',
  dSlide: 'Slide {n} de {total}', dPptx: 'Baixar PowerPoint', dPrev: 'Slide anterior', dNext: 'Próximo slide', dNotes: 'Notas do apresentador', dPolished: 'Revisado para qualidade',
  xTitle: 'Funcionários de IA neste computador', xHelp: 'Sua equipe de IA pode usar este computador em tarefas e turnos. Ler arquivos, abrir páginas e os apps abaixo acontece na hora; passos mais arriscados esperam sua aprovação na Caixa de entrada; senhas, bancos e configurações do sistema nunca são permitidos.', xOn: 'Funcionários de IA podem usar este computador', xApps: 'Apps que abrem sem perguntar (separados por vírgula)', xShortcuts: 'Atalhos que rodam sem perguntar (separados por vírgula)', xWrites: 'Arquivos novos nas pastas permitidas', xCommands: 'Comandos do terminal', xAuto: 'Sem perguntar', xAsk: 'Perguntar antes', xNever: 'Nunca', xSafe: 'Os seguros de só leitura sem perguntar, os outros perguntam', xHours: 'Só neste horário', xFrom: 'das', xTo: 'às', xSave: 'Salvar regras', xSaved: 'Salvo.', xLocal: 'No computador, permita também uma vez no Connector e reinicie-o:', xByAi: 'IA', xKindApp: 'Abrir app', xKindShortcut: 'Atalho', xPower: 'Depois dê a um funcionário o poder “Usar o computador da empresa” no Agent Studio.',
};

const de: Copy = {
  kEyebrow: 'Wissen', kTitle: 'Unternehmenswissen',
  kSub: 'Dokumente, Links und Apps, die dein KI-Team liest, bevor es antwortet. Nur dein Unternehmen sieht sie.',
  kAddText: 'Notiz oder Dokument hinzufügen', kName: 'Name', kText: 'Text einfügen: Preise, Richtlinien, Produkte, FAQs…',
  kFile: 'oder Datei hochladen (.txt, .md, .csv, .json)', kAddUrl: 'Webseite hinzufügen', kApp: 'Verbundene App lesen',
  kAppNone: 'Verbinde zuerst Notion, GitHub, Google Drive, Gmail, Google Kalender oder Outlook unter Integrationen.',
  kAdd: 'Hinzufügen', kSources: 'Quellen', kEmpty: 'Noch nichts hinzugefügt.', kSync: 'Neu synchronisieren', kDelete: 'Entfernen', kItems: '{n} Abschnitte',
  kSearch: 'Frage testen', kSearchPh: 'Frag etwas, das deine Dokumente beantworten', kNoHits: 'Nichts gefunden.', kSaved: 'Hinzugefügt. Dein KI-Team kann es jetzt nutzen.',
  kErr: 'Das hat nicht geklappt. Bitte erneut versuchen.', kLimit: 'Das Limit für Wissensquellen in deinem Tarif ist erreicht.', kBadUrl: 'Gib einen vollständigen https://-Link an.',
  kTooShort: 'Der Text ist zu kurz.', kManagersOnly: 'Nur Inhaber, Admins und Manager können Wissen hinzufügen oder entfernen.',
  sEyebrow: 'Fähigkeiten', sTitle: 'Fähigkeiten-Bibliothek',
  sSub: 'Arbeitsweisen, denen deine KI-Mitarbeiter folgen, wenn eine Aufgabe passt. Für das ganze Team oder einen Mitarbeiter installieren.',
  sLibrary: 'Bibliothek', sInstalled: 'Installiert', sInstall: 'Installieren', sFor: 'Für', sTeam: 'Ganzes Team', sCustom: 'Eigene Fähigkeit schreiben',
  sInstr: 'Die Schritte, denen der Mitarbeiter folgen soll', sOn: 'An', sOff: 'Aus', sRemove: 'Entfernen', sEmpty: 'Noch keine Fähigkeiten installiert.', sDone: 'Installiert.',
  wEyebrow: 'Workflows', wTitle: 'Workflows',
  wSub: 'Eine Kette von Schritten, jeder von einem KI-Mitarbeiter erledigt; jeder Schritt bekommt das vorige Ergebnis. Läuft auf dem Server, auch wenn die App geschlossen ist.',
  wNew: 'Neuer Workflow', wEdit: 'Bearbeiten', wName: 'Name', wDesc: 'Wofür (optional)', wSteps: 'Schritte', wAddStep: 'Schritt hinzufügen',
  wStepPh: 'Was dieser Mitarbeiter mit der Eingabe tun soll', wAgent: 'Mitarbeiter', wTrigger: 'Startet', wManual: 'Von Hand', wSchedule: 'Nach Zeitplan',
  wWebhook: 'Aus einer anderen App (Webhook)', wHourly: 'Stündlich', wDaily: 'Täglich', wWeekly: 'Wöchentlich', wAt: 'um', wSave: 'Speichern', wCancel: 'Abbrechen',
  wRun: 'Jetzt ausführen', wInput: 'Eingabe für den ersten Schritt (optional)', wRuns: 'Letzte Läufe', wHook: 'Webhook-Link erstellen',
  wHookShown: 'Kopiere den Link jetzt: Er wird nur einmal angezeigt. Wer ihn hat, kann den Workflow starten.', wDelete: 'Löschen', wActive: 'Aktiv',
  wEmpty: 'Noch keine Workflows.', wStarted: 'Gestartet. Verfolge die Schritte unter Aufgaben.', wStep: 'Schritt {n}', wNoSteps: 'Füge mindestens einen Schritt mit Mitarbeiter hinzu.',
  wNext: 'Nächster Lauf', wRunning: 'läuft', wCompleted: 'fertig', wFailed: 'fehlgeschlagen', wSaved: 'Gespeichert.',
  fGood: 'Guter Bericht', fBad: 'Nicht gut', fNote: 'Was soll besser werden? (optional)', fSend: 'Senden', fThanks: 'Danke. Der Mitarbeiter lernt daraus.',
  cTitle: 'Zwei-Wege-Chat mit deinem CEO', cOn: 'Einschalten', cOff: 'Ausschalten', cIsOn: 'An',
  cHelp: 'Was du hier schreibst, geht an deinen CEO, der im selben Chat antwortet. Freigaben kommen mit Buttons Freigeben / Ablehnen.',
  cAppSecret: 'App-Secret (Meta-App-Einstellungen)', cCallback: 'Callback-URL', cVerify: 'Verify-Token',
  cMetaHelp: 'Trage in deiner Meta-App diese Callback-URL und das Verify-Token für WhatsApp-Webhooks ein.',
  aAsk: '{name} fragen', aFound: 'Was gefunden wurde',
  dSlide: 'Folie {n} von {total}', dPptx: 'PowerPoint herunterladen', dPrev: 'Vorherige Folie', dNext: 'Nächste Folie', dNotes: 'Sprechernotizen', dPolished: 'Auf Qualität geprüft',
  xTitle: 'KI-Mitarbeiter auf diesem Computer', xHelp: 'Dein KI-Team darf diesen Computer in Aufgaben und Schichten nutzen. Dateien lesen, Seiten und die Apps unten öffnen geschieht sofort; riskantere Schritte warten im Posteingang auf deine Freigabe; Passwörter, Banking und Systemeinstellungen sind nie erlaubt.', xOn: 'KI-Mitarbeiter dürfen diesen Computer nutzen', xApps: 'Apps, die ohne Nachfrage geöffnet werden (mit Komma)', xShortcuts: 'Kurzbefehle ohne Nachfrage (mit Komma)', xWrites: 'Neue Dateien in den erlaubten Ordnern', xCommands: 'Terminal-Befehle', xAuto: 'Ohne Nachfrage', xAsk: 'Vorher fragen', xNever: 'Nie', xSafe: 'Sichere Lesebefehle ohne Nachfrage, der Rest fragt', xHours: 'Nur zu diesen Zeiten', xFrom: 'von', xTo: 'bis', xSave: 'Regeln speichern', xSaved: 'Gespeichert.', xLocal: 'Auf dem Computer auch einmal im Connector erlauben und ihn neu starten:', xByAi: 'KI', xKindApp: 'App öffnen', xKindShortcut: 'Kurzbefehl', xPower: 'Gib dann einem Mitarbeiter im Agent Studio die Fähigkeit „Firmencomputer nutzen“.',
};

const fr: Copy = {
  kEyebrow: 'Connaissances', kTitle: 'Connaissances de l’entreprise',
  kSub: 'Documents, liens et apps que votre équipe IA lit avant de répondre. Seule votre entreprise peut les voir.',
  kAddText: 'Ajouter une note ou un document', kName: 'Nom', kText: 'Collez le texte : prix, règles, produits, FAQ…',
  kFile: 'ou importez un fichier (.txt, .md, .csv, .json)', kAddUrl: 'Ajouter une page web', kApp: 'Lire une app connectée',
  kAppNone: 'Connectez d’abord Notion, GitHub, Google Drive, Gmail, Google Agenda ou Outlook dans Intégrations.',
  kAdd: 'Ajouter', kSources: 'Sources', kEmpty: 'Rien pour l’instant.', kSync: 'Resynchroniser', kDelete: 'Retirer', kItems: '{n} passages',
  kSearch: 'Essayez une question', kSearchPh: 'Posez une question à laquelle vos documents répondent', kNoHits: 'Rien trouvé.', kSaved: 'Ajouté. Votre équipe IA peut l’utiliser.',
  kErr: 'Cela n’a pas fonctionné. Réessayez.', kLimit: 'La limite de sources de votre offre est atteinte.', kBadUrl: 'Indiquez un lien https:// complet.',
  kTooShort: 'Le texte est trop court.', kManagersOnly: 'Seuls les propriétaires, admins et managers peuvent ajouter ou retirer des connaissances.',
  sEyebrow: 'Compétences', sTitle: 'Bibliothèque de compétences',
  sSub: 'Des façons de travailler que vos employés IA suivent quand la tâche correspond. À installer pour toute l’équipe ou un employé.',
  sLibrary: 'Bibliothèque', sInstalled: 'Installées', sInstall: 'Installer', sFor: 'Pour', sTeam: 'Toute l’équipe', sCustom: 'Écrire votre propre compétence',
  sInstr: 'Les étapes que l’employé doit suivre', sOn: 'Active', sOff: 'Inactive', sRemove: 'Retirer', sEmpty: 'Aucune compétence installée.', sDone: 'Installée.',
  wEyebrow: 'Workflows', wTitle: 'Workflows',
  wSub: 'Une chaîne d’étapes, chacune faite par un employé IA ; chaque étape reçoit le résultat précédent. Tourne sur le serveur, même app fermée.',
  wNew: 'Nouveau workflow', wEdit: 'Modifier', wName: 'Nom', wDesc: 'À quoi il sert (facultatif)', wSteps: 'Étapes', wAddStep: 'Ajouter une étape',
  wStepPh: 'Ce que cet employé doit faire avec l’entrée', wAgent: 'Employé', wTrigger: 'Démarre', wManual: 'À la main', wSchedule: 'Selon un horaire',
  wWebhook: 'Depuis une autre app (webhook)', wHourly: 'Toutes les heures', wDaily: 'Chaque jour', wWeekly: 'Chaque semaine', wAt: 'à', wSave: 'Enregistrer', wCancel: 'Annuler',
  wRun: 'Lancer', wInput: 'Entrée pour la première étape (facultatif)', wRuns: 'Exécutions récentes', wHook: 'Créer un lien webhook',
  wHookShown: 'Copiez ce lien maintenant : il ne s’affiche qu’une fois. Quiconque l’a peut lancer le workflow.', wDelete: 'Supprimer', wActive: 'Actif',
  wEmpty: 'Aucun workflow.', wStarted: 'Lancé. Suivez les étapes dans Tâches.', wStep: 'Étape {n}', wNoSteps: 'Ajoutez au moins une étape avec un employé.',
  wNext: 'Prochaine exécution', wRunning: 'en cours', wCompleted: 'terminé', wFailed: 'échec', wSaved: 'Enregistré.',
  fGood: 'Bon rapport', fBad: 'Pas bon', fNote: 'Qu’est-ce qui doit s’améliorer ? (facultatif)', fSend: 'Envoyer', fThanks: 'Merci. L’employé apprend de cela.',
  cTitle: 'Chat bidirectionnel avec votre CEO', cOn: 'Activer', cOff: 'Désactiver', cIsOn: 'Actif',
  cHelp: 'Ce que vous écrivez ici va à votre CEO, qui répond dans la même conversation. Les validations arrivent avec des boutons Approuver / Refuser.',
  cAppSecret: 'App secret (réglages de l’app Meta)', cCallback: 'URL de rappel', cVerify: 'Jeton de vérification',
  cMetaHelp: 'Dans votre app Meta, indiquez cette URL de rappel et ce jeton pour les webhooks WhatsApp.',
  aAsk: 'Demander à {name}', aFound: 'Ce qui a été trouvé',
  dSlide: 'Diapositive {n} sur {total}', dPptx: 'Télécharger PowerPoint', dPrev: 'Diapositive précédente', dNext: 'Diapositive suivante', dNotes: 'Notes de l’orateur', dPolished: 'Relu pour la qualité',
  xTitle: 'Employés IA sur cet ordinateur', xHelp: 'Votre équipe IA peut utiliser cet ordinateur dans ses tâches et ses horaires. Lire des fichiers, ouvrir des pages et les apps ci-dessous se fait tout de suite ; les étapes plus risquées attendent votre accord dans la Boîte de réception ; mots de passe, banque et réglages système ne sont jamais permis.', xOn: 'Les employés IA peuvent utiliser cet ordinateur', xApps: 'Apps ouvertes sans demander (séparées par des virgules)', xShortcuts: 'Raccourcis lancés sans demander (séparés par des virgules)', xWrites: 'Nouveaux fichiers dans les dossiers autorisés', xCommands: 'Commandes du terminal', xAuto: 'Sans demander', xAsk: 'Me demander', xNever: 'Jamais', xSafe: 'Les sûres en lecture seule sans demander, les autres me demandent', xHours: 'Seulement à ces heures', xFrom: 'de', xTo: 'à', xSave: 'Enregistrer les règles', xSaved: 'Enregistré.', xLocal: 'Sur l’ordinateur, autorisez-le aussi une fois dans le Connector puis relancez-le :', xByAi: 'IA', xKindApp: 'Ouvrir une app', xKindShortcut: 'Raccourci', xPower: 'Donnez ensuite à un employé le pouvoir « Utiliser l’ordinateur de l’entreprise » dans Agent Studio.',
};

const zh: Copy = {
  kEyebrow: '知识库', kTitle: '公司知识库',
  kSub: '你的 AI 团队在回答前会阅读的文档、链接和应用。只有你的公司可以看到。',
  kAddText: '添加笔记或文档', kName: '名称', kText: '粘贴文本：价格、政策、产品信息、常见问题…',
  kFile: '或上传文件（.txt、.md、.csv、.json）', kAddUrl: '添加网页', kApp: '读取已连接的应用',
  kAppNone: '请先在集成中连接 Notion、GitHub、Google 云端硬盘、Gmail、Google 日历或 Outlook。',
  kAdd: '添加', kSources: '来源', kEmpty: '还没有添加内容。', kSync: '重新同步', kDelete: '移除', kItems: '{n} 个段落',
  kSearch: '试着提问', kSearchPh: '问一个你的文档能回答的问题', kNoHits: '没有找到结果。', kSaved: '已添加，AI 团队现在可以使用。',
  kErr: '操作失败，请重试。', kLimit: '已达到你的套餐的知识来源上限。', kBadUrl: '请填写完整的 https:// 链接。',
  kTooShort: '文本太短。', kManagersOnly: '只有所有者、管理员和经理可以添加或移除知识。',
  sEyebrow: '技能', sTitle: '技能库',
  sSub: '当任务匹配时 AI 员工遵循的工作方式。可为整个团队或单个员工安装。',
  sLibrary: '技能库', sInstalled: '已安装', sInstall: '安装', sFor: '用于', sTeam: '整个团队', sCustom: '编写自己的技能',
  sInstr: '员工应遵循的步骤', sOn: '开启', sOff: '关闭', sRemove: '移除', sEmpty: '还没有安装技能。', sDone: '已安装。',
  wEyebrow: '工作流', wTitle: '工作流',
  wSub: '一系列步骤，每步由一名 AI 员工完成，并接收上一步的结果。在服务器上运行，即使关闭应用也会继续。',
  wNew: '新建工作流', wEdit: '编辑', wName: '名称', wDesc: '用途（可选）', wSteps: '步骤', wAddStep: '添加步骤',
  wStepPh: '该员工应如何处理输入', wAgent: '员工', wTrigger: '启动方式', wManual: '手动', wSchedule: '定时',
  wWebhook: '来自其他应用（webhook）', wHourly: '每小时', wDaily: '每天', wWeekly: '每周', wAt: '时间', wSave: '保存', wCancel: '取消',
  wRun: '立即运行', wInput: '第一步的输入（可选）', wRuns: '最近运行', wHook: '创建 webhook 链接',
  wHookShown: '请立即复制此链接：它只显示一次。任何拥有链接的人都能启动该工作流。', wDelete: '删除', wActive: '启用',
  wEmpty: '还没有工作流。', wStarted: '已启动。在任务中查看各步骤。', wStep: '第 {n} 步', wNoSteps: '请至少添加一个带员工的步骤。',
  wNext: '下次运行', wRunning: '运行中', wCompleted: '已完成', wFailed: '失败', wSaved: '已保存。',
  fGood: '报告很好', fBad: '不够好', fNote: '哪里需要改进？（可选）', fSend: '发送', fThanks: '谢谢，员工会从中学习。',
  cTitle: '与 CEO 双向聊天', cOn: '开启', cOff: '关闭', cIsOn: '已开启',
  cHelp: '你在这里发送的消息会交给你的 CEO，CEO 会在同一聊天中回复。审批会带有批准 / 拒绝按钮。',
  cAppSecret: 'App secret（Meta 应用设置）', cCallback: '回调 URL', cVerify: '验证令牌',
  cMetaHelp: '在你的 Meta 应用中，为 WhatsApp webhook 设置此回调 URL 和验证令牌。',
  aAsk: '问 {name}', aFound: '找到的内容',
  dSlide: '第 {n} 张，共 {total} 张', dPptx: '下载 PowerPoint', dPrev: '上一张', dNext: '下一张', dNotes: '演讲者备注', dPolished: '已经过质量审核',
  xTitle: '这台电脑上的 AI 员工', xHelp: '让 AI 团队在任务和班次中使用这台电脑。读取文件、打开网页和下面的应用会立即执行；风险较高的步骤会在收件箱等待你的批准；密码、银行和系统设置永远不允许。', xOn: 'AI 员工可以使用这台电脑', xApps: '无需询问即可打开的应用（用逗号分隔）', xShortcuts: '无需询问即可运行的快捷指令（用逗号分隔）', xWrites: '允许文件夹中的新文件', xCommands: '终端命令', xAuto: '无需询问', xAsk: '先问我', xNever: '从不', xSafe: '安全的只读命令无需询问，其余先问我', xHours: '仅限这些时间', xFrom: '从', xTo: '到', xSave: '保存规则', xSaved: '已保存。', xLocal: '在电脑上，也要在 Connector 中允许一次，然后重新启动：', xByAi: 'AI', xKindApp: '打开应用', xKindShortcut: '快捷指令', xPower: '然后在 Agent Studio 中给员工“使用公司电脑”能力。',
};

const ar: Copy = {
  kEyebrow: 'المعرفة', kTitle: 'معرفة الشركة',
  kSub: 'مستندات وروابط وتطبيقات يقرؤها فريق الذكاء الاصطناعي قبل أن يجيب. لا يراها إلا شركتك.',
  kAddText: 'إضافة ملاحظة أو مستند', kName: 'الاسم', kText: 'الصق النص: الأسعار، السياسات، المنتجات، الأسئلة الشائعة…',
  kFile: 'أو ارفع ملفًا (.txt، .md، .csv، .json)', kAddUrl: 'إضافة صفحة ويب', kApp: 'قراءة تطبيق متصل',
  kAppNone: 'اربط أولاً Notion أو GitHub أو Google Drive أو Gmail أو تقويم Google أو Outlook من صفحة التكاملات.',
  kAdd: 'إضافة', kSources: 'المصادر', kEmpty: 'لم تتم إضافة شيء بعد.', kSync: 'مزامنة مجددًا', kDelete: 'إزالة', kItems: '{n} مقاطع',
  kSearch: 'جرّب سؤالاً', kSearchPh: 'اسأل شيئًا تجيب عنه مستنداتك', kNoHits: 'لم يُعثر على شيء.', kSaved: 'تمت الإضافة. يمكن لفريقك استخدامها الآن.',
  kErr: 'لم ينجح ذلك. حاول مرة أخرى.', kLimit: 'تم بلوغ حد مصادر المعرفة في خطتك.', kBadUrl: 'أدخل رابط https:// كاملاً.',
  kTooShort: 'النص قصير جدًا.', kManagersOnly: 'لا يضيف المعرفة أو يزيلها إلا المالكون والمسؤولون والمديرون.',
  sEyebrow: 'المهارات', sTitle: 'مكتبة المهارات',
  sSub: 'طرق عمل يتبعها موظفو الذكاء الاصطناعي عندما تناسب المهمة. ثبّتها للفريق كله أو لموظف واحد.',
  sLibrary: 'المكتبة', sInstalled: 'المثبتة', sInstall: 'تثبيت', sFor: 'لـ', sTeam: 'الفريق كله', sCustom: 'اكتب مهارتك الخاصة',
  sInstr: 'الخطوات التي يتبعها الموظف', sOn: 'مفعّلة', sOff: 'متوقفة', sRemove: 'إزالة', sEmpty: 'لا توجد مهارات مثبتة بعد.', sDone: 'تم التثبيت.',
  wEyebrow: 'سير العمل', wTitle: 'سير العمل',
  wSub: 'سلسلة خطوات، ينفذ كل خطوة موظف ذكاء اصطناعي ويتلقى نتيجة الخطوة السابقة. تعمل على الخادم حتى مع إغلاق التطبيق.',
  wNew: 'سير عمل جديد', wEdit: 'تعديل', wName: 'الاسم', wDesc: 'الغرض (اختياري)', wSteps: 'الخطوات', wAddStep: 'إضافة خطوة',
  wStepPh: 'ما الذي يفعله هذا الموظف بالمدخلات', wAgent: 'الموظف', wTrigger: 'يبدأ', wManual: 'يدويًا', wSchedule: 'حسب جدول',
  wWebhook: 'من تطبيق آخر (webhook)', wHourly: 'كل ساعة', wDaily: 'كل يوم', wWeekly: 'كل أسبوع', wAt: 'الساعة', wSave: 'حفظ', wCancel: 'إلغاء',
  wRun: 'تشغيل الآن', wInput: 'مدخلات الخطوة الأولى (اختياري)', wRuns: 'التشغيلات الأخيرة', wHook: 'إنشاء رابط webhook',
  wHookShown: 'انسخ الرابط الآن: يظهر مرة واحدة فقط. أي شخص يملكه يمكنه تشغيل سير العمل.', wDelete: 'حذف', wActive: 'مفعّل',
  wEmpty: 'لا يوجد سير عمل بعد.', wStarted: 'بدأ. تابع الخطوات في المهام.', wStep: 'الخطوة {n}', wNoSteps: 'أضف خطوة واحدة على الأقل مع موظف.',
  wNext: 'التشغيل التالي', wRunning: 'قيد التشغيل', wCompleted: 'اكتمل', wFailed: 'فشل', wSaved: 'تم الحفظ.',
  fGood: 'تقرير جيد', fBad: 'ليس جيدًا', fNote: 'ما الذي يجب تحسينه؟ (اختياري)', fSend: 'إرسال', fThanks: 'شكرًا. يتعلم الموظف من ذلك.',
  cTitle: 'دردشة ثنائية الاتجاه مع الرئيس التنفيذي', cOn: 'تشغيل', cOff: 'إيقاف', cIsOn: 'مفعّلة',
  cHelp: 'ما تكتبه هنا يصل إلى الرئيس التنفيذي الذي يرد في المحادثة نفسها. تصل الموافقات مع زري موافقة / رفض.',
  cAppSecret: 'App secret (إعدادات تطبيق Meta)', cCallback: 'رابط الاستدعاء', cVerify: 'رمز التحقق',
  cMetaHelp: 'في تطبيق Meta، اضبط رابط الاستدعاء ورمز التحقق هذين لـ webhooks واتساب.',
  aAsk: 'اسأل {name}', aFound: 'ما الذي وجده',
  dSlide: 'الشريحة {n} من {total}', dPptx: 'تنزيل PowerPoint', dPrev: 'الشريحة السابقة', dNext: 'الشريحة التالية', dNotes: 'ملاحظات المتحدث', dPolished: 'رُوجع للجودة',
  xTitle: 'موظفو الذكاء الاصطناعي على هذا الحاسوب', xHelp: 'اسمح لفريق الذكاء الاصطناعي باستخدام هذا الحاسوب في المهام والورديات. قراءة الملفات وفتح الصفحات والتطبيقات أدناه تتم فورًا؛ الخطوات الأكثر خطورة تنتظر موافقتك في البريد الوارد؛ كلمات المرور والبنوك وإعدادات النظام غير مسموح بها أبدًا.', xOn: 'يمكن لموظفي الذكاء الاصطناعي استخدام هذا الحاسوب', xApps: 'تطبيقات تُفتح دون سؤال (مفصولة بفواصل)', xShortcuts: 'اختصارات تُشغَّل دون سؤال (مفصولة بفواصل)', xWrites: 'ملفات جديدة في المجلدات المسموح بها', xCommands: 'أوامر الطرفية', xAuto: 'دون سؤال', xAsk: 'اسألني أولًا', xNever: 'أبدًا', xSafe: 'الأوامر الآمنة للقراءة فقط دون سؤال، والباقي يسألني', xHours: 'في هذه الساعات فقط', xFrom: 'من', xTo: 'إلى', xSave: 'حفظ القواعد', xSaved: 'تم الحفظ.', xLocal: 'على الحاسوب، اسمح بذلك أيضًا مرة واحدة في Connector ثم أعد تشغيله:', xByAi: 'ذكاء', xKindApp: 'فتح تطبيق', xKindShortcut: 'اختصار', xPower: 'ثم امنح موظفًا قدرة «استخدام حاسوب الشركة» في Agent Studio.',
};

const COPY: Record<string, Copy> = { en, el, es, 'pt-BR': ptBR, de, fr, 'zh-CN': zh, ar };

/** The page text in the user's language, with {n}-style values filled in. */
export function useWorkspaceCopy() {
  const { lang } = useI18n();
  const c = COPY[lang] ?? en;
  return (key: keyof Copy, vars: Record<string, string | number> = {}) => c[key].replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ''));
}
export type WorkspaceKey = keyof Copy;
export const WORKSPACE_COPY = COPY;
