// Text for the Knowledge, Skills and Workflows pages, report feedback and two-way chat channels, in the 8 app languages.
// Kept next to the pages (like the Inbox's inline copy) so the shared locale files stay small.
import { useI18n } from '../../i18n/I18nProvider';

const en = {
  kEyebrow: 'Knowledge', kTitle: 'Company knowledge',
  kSub: 'Documents, links and apps your AI team reads before it answers. Only your company can see them.',
  kAddText: 'Add a note or document', kName: 'Name', kText: 'Paste the text: prices, policies, product details, FAQs…',
  kFile: 'or upload a file (.txt, .md, .csv, .json)', kAddUrl: 'Add a web page', kApp: 'Read a connected app',
  kAppNone: 'Connect Notion, GitHub, Google Drive, Gmail, Google Calendar or Outlook in Integrations first.',
  kAdd: 'Add', kSources: 'Sources', kEmpty: 'Nothing added yet.', kSync: 'Sync again', kDelete: 'Remove', kItems: '{n} passages',
  kSearch: 'Try a question', kSearchPh: 'Ask something your documents answer', kNoHits: 'Nothing found.', kSaved: 'Added. Your AI team can use it now.',
  kErr: 'That did not work. Try again.', kLimit: 'Your plan’s limit for knowledge sources is reached.', kBadUrl: 'Give a full https:// link.',
  kTooShort: 'The text is too short.', kManagersOnly: 'Only owners, admins and managers can add or remove knowledge.',
  sEyebrow: 'Skills', sTitle: 'Skills library',
  sSub: 'Ways of working your AI employees follow when a task matches. Install one for the whole team or for one employee.',
  sLibrary: 'Library', sInstalled: 'Installed', sInstall: 'Install', sFor: 'For', sTeam: 'Whole team', sCustom: 'Write your own skill',
  sInstr: 'The steps the employee should follow', sOn: 'On', sOff: 'Off', sRemove: 'Remove', sEmpty: 'No skills installed yet.', sDone: 'Installed.',
  wEyebrow: 'Workflows', wTitle: 'Workflows',
  wSub: 'A chain of steps, each done by an AI employee; every step gets the previous result. It runs on the server, even with the app closed.',
  wNew: 'New workflow', wEdit: 'Edit', wName: 'Name', wDesc: 'What it is for (optional)', wSteps: 'Steps', wAddStep: 'Add a step',
  wStepPh: 'What this employee should do with the input', wAgent: 'Employee', wTrigger: 'Starts', wManual: 'By hand', wSchedule: 'On a schedule',
  wWebhook: 'From another app (webhook)', wHourly: 'Every hour', wDaily: 'Every day', wWeekly: 'Every week', wAt: 'at', wSave: 'Save', wCancel: 'Cancel',
  wRun: 'Run now', wInput: 'Input for the first step (optional)', wRuns: 'Recent runs', wHook: 'Create webhook link',
  wHookShown: 'Copy this link now: it is shown only once. Anyone with it can start the workflow.', wDelete: 'Delete', wActive: 'Active',
  wEmpty: 'No workflows yet.', wStarted: 'Started. Follow the steps in Tasks.', wStep: 'Step {n}', wNoSteps: 'Add at least one step with an employee.',
  wNext: 'Next run', wRunning: 'running', wCompleted: 'done', wFailed: 'failed', wSaved: 'Saved.',
  fGood: 'Good report', fBad: 'Not good', fNote: 'What should be better? (optional)', fSend: 'Send', fThanks: 'Thanks. The employee learns from this.',
  cTitle: 'Two-way chat with your CEO', cOn: 'Turn on', cOff: 'Turn off', cIsOn: 'On',
  cHelp: 'Messages you send here go to your CEO, who answers in the same chat. Approvals arrive with Approve / Reject buttons.',
  cAppSecret: 'App secret (Meta app settings)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'In your Meta app, set this callback URL and verify token for WhatsApp webhooks.',
};
type Copy = typeof en;

const el: Copy = {
  kEyebrow: 'Γνώση', kTitle: 'Γνώση εταιρείας',
  kSub: 'Έγγραφα, σύνδεσμοι και εφαρμογές που διαβάζει η ομάδα AI πριν απαντήσει. Τα βλέπει μόνο η εταιρεία σας.',
  kAddText: 'Προσθήκη σημείωσης ή εγγράφου', kName: 'Όνομα', kText: 'Επικολλήστε το κείμενο: τιμές, πολιτικές, προϊόντα, συχνές ερωτήσεις…',
  kFile: 'ή ανεβάστε αρχείο (.txt, .md, .csv, .json)', kAddUrl: 'Προσθήκη ιστοσελίδας', kApp: 'Ανάγνωση συνδεδεμένης εφαρμογής',
  kAppNone: 'Συνδέστε πρώτα Notion, GitHub, Google Drive, Gmail, Google Calendar ή Outlook στις Ενσωματώσεις.',
  kAdd: 'Προσθήκη', kSources: 'Πηγές', kEmpty: 'Δεν έχει προστεθεί τίποτα ακόμα.', kSync: 'Συγχρονισμός', kDelete: 'Αφαίρεση', kItems: '{n} αποσπάσματα',
  kSearch: 'Δοκιμάστε μια ερώτηση', kSearchPh: 'Ρωτήστε κάτι που απαντούν τα έγγραφά σας', kNoHits: 'Δεν βρέθηκε τίποτα.', kSaved: 'Προστέθηκε. Η ομάδα AI μπορεί να το χρησιμοποιήσει.',
  kErr: 'Δεν έγινε. Δοκιμάστε ξανά.', kLimit: 'Συμπληρώθηκε το όριο πηγών γνώσης του πακέτου σας.', kBadUrl: 'Δώστε πλήρη σύνδεσμο https://.',
  kTooShort: 'Το κείμενο είναι πολύ μικρό.', kManagersOnly: 'Μόνο ιδιοκτήτες, διαχειριστές και managers προσθέτουν ή αφαιρούν γνώση.',
  sEyebrow: 'Δεξιότητες', sTitle: 'Βιβλιοθήκη δεξιοτήτων',
  sSub: 'Τρόποι δουλειάς που ακολουθούν οι AI υπάλληλοι όταν ταιριάζει η εργασία. Εγκαταστήστε για όλη την ομάδα ή για έναν υπάλληλο.',
  sLibrary: 'Βιβλιοθήκη', sInstalled: 'Εγκατεστημένες', sInstall: 'Εγκατάσταση', sFor: 'Για', sTeam: 'Όλη η ομάδα', sCustom: 'Γράψτε δική σας δεξιότητα',
  sInstr: 'Τα βήματα που ακολουθεί ο υπάλληλος', sOn: 'Ενεργή', sOff: 'Ανενεργή', sRemove: 'Αφαίρεση', sEmpty: 'Δεν υπάρχουν δεξιότητες ακόμα.', sDone: 'Εγκαταστάθηκε.',
  wEyebrow: 'Ροές εργασίας', wTitle: 'Ροές εργασίας',
  wSub: 'Αλυσίδα βημάτων, το καθένα από έναν AI υπάλληλο· κάθε βήμα παίρνει το αποτέλεσμα του προηγούμενου. Τρέχει στον server, ακόμα και με την εφαρμογή κλειστή.',
  wNew: 'Νέα ροή', wEdit: 'Επεξεργασία', wName: 'Όνομα', wDesc: 'Σκοπός (προαιρετικό)', wSteps: 'Βήματα', wAddStep: 'Προσθήκη βήματος',
  wStepPh: 'Τι κάνει αυτός ο υπάλληλος με την είσοδο', wAgent: 'Υπάλληλος', wTrigger: 'Ξεκινά', wManual: 'Χειροκίνητα', wSchedule: 'Με πρόγραμμα',
  wWebhook: 'Από άλλη εφαρμογή (webhook)', wHourly: 'Κάθε ώρα', wDaily: 'Κάθε μέρα', wWeekly: 'Κάθε εβδομάδα', wAt: 'στις', wSave: 'Αποθήκευση', wCancel: 'Άκυρο',
  wRun: 'Εκτέλεση τώρα', wInput: 'Είσοδος για το πρώτο βήμα (προαιρετικό)', wRuns: 'Πρόσφατες εκτελέσεις', wHook: 'Δημιουργία συνδέσμου webhook',
  wHookShown: 'Αντιγράψτε τον σύνδεσμο τώρα: εμφανίζεται μόνο μία φορά. Όποιος τον έχει μπορεί να ξεκινήσει τη ροή.', wDelete: 'Διαγραφή', wActive: 'Ενεργή',
  wEmpty: 'Δεν υπάρχουν ροές ακόμα.', wStarted: 'Ξεκίνησε. Δείτε τα βήματα στις Εργασίες.', wStep: 'Βήμα {n}', wNoSteps: 'Προσθέστε τουλάχιστον ένα βήμα με υπάλληλο.',
  wNext: 'Επόμενη εκτέλεση', wRunning: 'σε εξέλιξη', wCompleted: 'ολοκληρώθηκε', wFailed: 'απέτυχε', wSaved: 'Αποθηκεύτηκε.',
  fGood: 'Καλή αναφορά', fBad: 'Όχι καλή', fNote: 'Τι να βελτιωθεί; (προαιρετικό)', fSend: 'Αποστολή', fThanks: 'Ευχαριστούμε. Ο υπάλληλος μαθαίνει από αυτό.',
  cTitle: 'Συνομιλία διπλής κατεύθυνσης με τον CEO', cOn: 'Ενεργοποίηση', cOff: 'Απενεργοποίηση', cIsOn: 'Ενεργή',
  cHelp: 'Ό,τι γράφετε εδώ πηγαίνει στον CEO σας, που απαντά στην ίδια συνομιλία. Οι εγκρίσεις έρχονται με κουμπιά Έγκριση / Απόρριψη.',
  cAppSecret: 'App secret (ρυθμίσεις εφαρμογής Meta)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'Στην εφαρμογή Meta, βάλτε αυτό το callback URL και verify token για τα webhooks του WhatsApp.',
};

const es: Copy = {
  kEyebrow: 'Conocimiento', kTitle: 'Conocimiento de la empresa',
  kSub: 'Documentos, enlaces y apps que tu equipo de IA lee antes de responder. Solo tu empresa puede verlos.',
  kAddText: 'Añadir una nota o documento', kName: 'Nombre', kText: 'Pega el texto: precios, políticas, productos, preguntas frecuentes…',
  kFile: 'o sube un archivo (.txt, .md, .csv, .json)', kAddUrl: 'Añadir una página web', kApp: 'Leer una app conectada',
  kAppNone: 'Conecta primero Notion, GitHub, Google Drive, Gmail, Google Calendar u Outlook en Integraciones.',
  kAdd: 'Añadir', kSources: 'Fuentes', kEmpty: 'Aún no hay nada.', kSync: 'Sincronizar', kDelete: 'Quitar', kItems: '{n} fragmentos',
  kSearch: 'Prueba una pregunta', kSearchPh: 'Pregunta algo que respondan tus documentos', kNoHits: 'No se encontró nada.', kSaved: 'Añadido. Tu equipo de IA ya puede usarlo.',
  kErr: 'No funcionó. Inténtalo de nuevo.', kLimit: 'Has alcanzado el límite de fuentes de tu plan.', kBadUrl: 'Escribe un enlace https:// completo.',
  kTooShort: 'El texto es demasiado corto.', kManagersOnly: 'Solo propietarios, administradores y managers pueden añadir o quitar conocimiento.',
  sEyebrow: 'Habilidades', sTitle: 'Biblioteca de habilidades',
  sSub: 'Formas de trabajar que tus empleados de IA siguen cuando la tarea encaja. Instala una para todo el equipo o para un empleado.',
  sLibrary: 'Biblioteca', sInstalled: 'Instaladas', sInstall: 'Instalar', sFor: 'Para', sTeam: 'Todo el equipo', sCustom: 'Escribe tu propia habilidad',
  sInstr: 'Los pasos que debe seguir el empleado', sOn: 'Activa', sOff: 'Inactiva', sRemove: 'Quitar', sEmpty: 'Aún no hay habilidades.', sDone: 'Instalada.',
  wEyebrow: 'Flujos de trabajo', wTitle: 'Flujos de trabajo',
  wSub: 'Una cadena de pasos, cada uno hecho por un empleado de IA; cada paso recibe el resultado anterior. Se ejecuta en el servidor, incluso con la app cerrada.',
  wNew: 'Nuevo flujo', wEdit: 'Editar', wName: 'Nombre', wDesc: 'Para qué sirve (opcional)', wSteps: 'Pasos', wAddStep: 'Añadir paso',
  wStepPh: 'Qué debe hacer este empleado con la entrada', wAgent: 'Empleado', wTrigger: 'Empieza', wManual: 'A mano', wSchedule: 'Con horario',
  wWebhook: 'Desde otra app (webhook)', wHourly: 'Cada hora', wDaily: 'Cada día', wWeekly: 'Cada semana', wAt: 'a las', wSave: 'Guardar', wCancel: 'Cancelar',
  wRun: 'Ejecutar ahora', wInput: 'Entrada para el primer paso (opcional)', wRuns: 'Ejecuciones recientes', wHook: 'Crear enlace webhook',
  wHookShown: 'Copia el enlace ahora: solo se muestra una vez. Quien lo tenga puede iniciar el flujo.', wDelete: 'Eliminar', wActive: 'Activo',
  wEmpty: 'Aún no hay flujos.', wStarted: 'Iniciado. Sigue los pasos en Tareas.', wStep: 'Paso {n}', wNoSteps: 'Añade al menos un paso con un empleado.',
  wNext: 'Próxima ejecución', wRunning: 'en curso', wCompleted: 'terminado', wFailed: 'falló', wSaved: 'Guardado.',
  fGood: 'Buen informe', fBad: 'No es bueno', fNote: '¿Qué debería mejorar? (opcional)', fSend: 'Enviar', fThanks: 'Gracias. El empleado aprende de esto.',
  cTitle: 'Chat bidireccional con tu CEO', cOn: 'Activar', cOff: 'Desactivar', cIsOn: 'Activo',
  cHelp: 'Lo que escribas aquí llega a tu CEO, que responde en el mismo chat. Las aprobaciones llegan con botones Aprobar / Rechazar.',
  cAppSecret: 'App secret (ajustes de la app de Meta)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'En tu app de Meta, configura esta callback URL y el verify token para los webhooks de WhatsApp.',
};

const ptBR: Copy = {
  kEyebrow: 'Conhecimento', kTitle: 'Conhecimento da empresa',
  kSub: 'Documentos, links e apps que sua equipe de IA lê antes de responder. Só a sua empresa pode vê-los.',
  kAddText: 'Adicionar nota ou documento', kName: 'Nome', kText: 'Cole o texto: preços, políticas, produtos, perguntas frequentes…',
  kFile: 'ou envie um arquivo (.txt, .md, .csv, .json)', kAddUrl: 'Adicionar página web', kApp: 'Ler um app conectado',
  kAppNone: 'Conecte primeiro Notion, GitHub, Google Drive, Gmail, Google Calendar ou Outlook em Integrações.',
  kAdd: 'Adicionar', kSources: 'Fontes', kEmpty: 'Nada adicionado ainda.', kSync: 'Sincronizar', kDelete: 'Remover', kItems: '{n} trechos',
  kSearch: 'Teste uma pergunta', kSearchPh: 'Pergunte algo que seus documentos respondem', kNoHits: 'Nada encontrado.', kSaved: 'Adicionado. Sua equipe de IA já pode usar.',
  kErr: 'Não deu certo. Tente de novo.', kLimit: 'O limite de fontes do seu plano foi atingido.', kBadUrl: 'Informe um link https:// completo.',
  kTooShort: 'O texto é curto demais.', kManagersOnly: 'Só proprietários, administradores e gerentes podem adicionar ou remover conhecimento.',
  sEyebrow: 'Habilidades', sTitle: 'Biblioteca de habilidades',
  sSub: 'Formas de trabalhar que seus funcionários de IA seguem quando a tarefa combina. Instale para toda a equipe ou para um funcionário.',
  sLibrary: 'Biblioteca', sInstalled: 'Instaladas', sInstall: 'Instalar', sFor: 'Para', sTeam: 'Toda a equipe', sCustom: 'Escreva sua própria habilidade',
  sInstr: 'Os passos que o funcionário deve seguir', sOn: 'Ativa', sOff: 'Inativa', sRemove: 'Remover', sEmpty: 'Nenhuma habilidade ainda.', sDone: 'Instalada.',
  wEyebrow: 'Fluxos de trabalho', wTitle: 'Fluxos de trabalho',
  wSub: 'Uma cadeia de passos, cada um feito por um funcionário de IA; cada passo recebe o resultado anterior. Roda no servidor, mesmo com o app fechado.',
  wNew: 'Novo fluxo', wEdit: 'Editar', wName: 'Nome', wDesc: 'Para que serve (opcional)', wSteps: 'Passos', wAddStep: 'Adicionar passo',
  wStepPh: 'O que este funcionário deve fazer com a entrada', wAgent: 'Funcionário', wTrigger: 'Começa', wManual: 'Manualmente', wSchedule: 'Com agenda',
  wWebhook: 'De outro app (webhook)', wHourly: 'A cada hora', wDaily: 'Todo dia', wWeekly: 'Toda semana', wAt: 'às', wSave: 'Salvar', wCancel: 'Cancelar',
  wRun: 'Executar agora', wInput: 'Entrada para o primeiro passo (opcional)', wRuns: 'Execuções recentes', wHook: 'Criar link de webhook',
  wHookShown: 'Copie o link agora: ele aparece só uma vez. Quem tiver o link pode iniciar o fluxo.', wDelete: 'Excluir', wActive: 'Ativo',
  wEmpty: 'Nenhum fluxo ainda.', wStarted: 'Iniciado. Acompanhe os passos em Tarefas.', wStep: 'Passo {n}', wNoSteps: 'Adicione pelo menos um passo com um funcionário.',
  wNext: 'Próxima execução', wRunning: 'em andamento', wCompleted: 'concluído', wFailed: 'falhou', wSaved: 'Salvo.',
  fGood: 'Bom relatório', fBad: 'Não ficou bom', fNote: 'O que deve melhorar? (opcional)', fSend: 'Enviar', fThanks: 'Obrigado. O funcionário aprende com isso.',
  cTitle: 'Chat de mão dupla com seu CEO', cOn: 'Ativar', cOff: 'Desativar', cIsOn: 'Ativo',
  cHelp: 'O que você escreve aqui vai para o seu CEO, que responde na mesma conversa. Aprovações chegam com botões Aprovar / Rejeitar.',
  cAppSecret: 'App secret (configurações do app Meta)', cCallback: 'Callback URL', cVerify: 'Verify token',
  cMetaHelp: 'No seu app Meta, configure esta callback URL e o verify token para os webhooks do WhatsApp.',
};

const de: Copy = {
  kEyebrow: 'Wissen', kTitle: 'Unternehmenswissen',
  kSub: 'Dokumente, Links und Apps, die dein KI-Team liest, bevor es antwortet. Nur dein Unternehmen sieht sie.',
  kAddText: 'Notiz oder Dokument hinzufügen', kName: 'Name', kText: 'Text einfügen: Preise, Richtlinien, Produkte, FAQs…',
  kFile: 'oder Datei hochladen (.txt, .md, .csv, .json)', kAddUrl: 'Webseite hinzufügen', kApp: 'Verbundene App lesen',
  kAppNone: 'Verbinde zuerst Notion, GitHub, Google Drive, Gmail, Google Kalender oder Outlook unter Integrationen.',
  kAdd: 'Hinzufügen', kSources: 'Quellen', kEmpty: 'Noch nichts hinzugefügt.', kSync: 'Neu synchronisieren', kDelete: 'Entfernen', kItems: '{n} Abschnitte',
  kSearch: 'Frage testen', kSearchPh: 'Frag etwas, das deine Dokumente beantworten', kNoHits: 'Nichts gefunden.', kSaved: 'Hinzugefügt. Dein KI-Team kann es jetzt nutzen.',
  kErr: 'Das hat nicht geklappt. Bitte erneut versuchen.', kLimit: 'Das Limit für Wissensquellen in deinem Tarif ist erreicht.', kBadUrl: 'Gib einen vollständigen https://-Link an.',
  kTooShort: 'Der Text ist zu kurz.', kManagersOnly: 'Nur Inhaber, Admins und Manager können Wissen hinzufügen oder entfernen.',
  sEyebrow: 'Fähigkeiten', sTitle: 'Fähigkeiten-Bibliothek',
  sSub: 'Arbeitsweisen, denen deine KI-Mitarbeiter folgen, wenn eine Aufgabe passt. Für das ganze Team oder einen Mitarbeiter installieren.',
  sLibrary: 'Bibliothek', sInstalled: 'Installiert', sInstall: 'Installieren', sFor: 'Für', sTeam: 'Ganzes Team', sCustom: 'Eigene Fähigkeit schreiben',
  sInstr: 'Die Schritte, denen der Mitarbeiter folgen soll', sOn: 'An', sOff: 'Aus', sRemove: 'Entfernen', sEmpty: 'Noch keine Fähigkeiten installiert.', sDone: 'Installiert.',
  wEyebrow: 'Workflows', wTitle: 'Workflows',
  wSub: 'Eine Kette von Schritten, jeder von einem KI-Mitarbeiter erledigt; jeder Schritt bekommt das vorige Ergebnis. Läuft auf dem Server, auch wenn die App geschlossen ist.',
  wNew: 'Neuer Workflow', wEdit: 'Bearbeiten', wName: 'Name', wDesc: 'Wofür (optional)', wSteps: 'Schritte', wAddStep: 'Schritt hinzufügen',
  wStepPh: 'Was dieser Mitarbeiter mit der Eingabe tun soll', wAgent: 'Mitarbeiter', wTrigger: 'Startet', wManual: 'Von Hand', wSchedule: 'Nach Zeitplan',
  wWebhook: 'Aus einer anderen App (Webhook)', wHourly: 'Stündlich', wDaily: 'Täglich', wWeekly: 'Wöchentlich', wAt: 'um', wSave: 'Speichern', wCancel: 'Abbrechen',
  wRun: 'Jetzt ausführen', wInput: 'Eingabe für den ersten Schritt (optional)', wRuns: 'Letzte Läufe', wHook: 'Webhook-Link erstellen',
  wHookShown: 'Kopiere den Link jetzt: Er wird nur einmal angezeigt. Wer ihn hat, kann den Workflow starten.', wDelete: 'Löschen', wActive: 'Aktiv',
  wEmpty: 'Noch keine Workflows.', wStarted: 'Gestartet. Verfolge die Schritte unter Aufgaben.', wStep: 'Schritt {n}', wNoSteps: 'Füge mindestens einen Schritt mit Mitarbeiter hinzu.',
  wNext: 'Nächster Lauf', wRunning: 'läuft', wCompleted: 'fertig', wFailed: 'fehlgeschlagen', wSaved: 'Gespeichert.',
  fGood: 'Guter Bericht', fBad: 'Nicht gut', fNote: 'Was soll besser werden? (optional)', fSend: 'Senden', fThanks: 'Danke. Der Mitarbeiter lernt daraus.',
  cTitle: 'Zwei-Wege-Chat mit deinem CEO', cOn: 'Einschalten', cOff: 'Ausschalten', cIsOn: 'An',
  cHelp: 'Was du hier schreibst, geht an deinen CEO, der im selben Chat antwortet. Freigaben kommen mit Buttons Freigeben / Ablehnen.',
  cAppSecret: 'App-Secret (Meta-App-Einstellungen)', cCallback: 'Callback-URL', cVerify: 'Verify-Token',
  cMetaHelp: 'Trage in deiner Meta-App diese Callback-URL und das Verify-Token für WhatsApp-Webhooks ein.',
};

const fr: Copy = {
  kEyebrow: 'Connaissances', kTitle: 'Connaissances de l’entreprise',
  kSub: 'Documents, liens et apps que votre équipe IA lit avant de répondre. Seule votre entreprise peut les voir.',
  kAddText: 'Ajouter une note ou un document', kName: 'Nom', kText: 'Collez le texte : prix, règles, produits, FAQ…',
  kFile: 'ou importez un fichier (.txt, .md, .csv, .json)', kAddUrl: 'Ajouter une page web', kApp: 'Lire une app connectée',
  kAppNone: 'Connectez d’abord Notion, GitHub, Google Drive, Gmail, Google Agenda ou Outlook dans Intégrations.',
  kAdd: 'Ajouter', kSources: 'Sources', kEmpty: 'Rien pour l’instant.', kSync: 'Resynchroniser', kDelete: 'Retirer', kItems: '{n} passages',
  kSearch: 'Essayez une question', kSearchPh: 'Posez une question à laquelle vos documents répondent', kNoHits: 'Rien trouvé.', kSaved: 'Ajouté. Votre équipe IA peut l’utiliser.',
  kErr: 'Cela n’a pas fonctionné. Réessayez.', kLimit: 'La limite de sources de votre offre est atteinte.', kBadUrl: 'Indiquez un lien https:// complet.',
  kTooShort: 'Le texte est trop court.', kManagersOnly: 'Seuls les propriétaires, admins et managers peuvent ajouter ou retirer des connaissances.',
  sEyebrow: 'Compétences', sTitle: 'Bibliothèque de compétences',
  sSub: 'Des façons de travailler que vos employés IA suivent quand la tâche correspond. À installer pour toute l’équipe ou un employé.',
  sLibrary: 'Bibliothèque', sInstalled: 'Installées', sInstall: 'Installer', sFor: 'Pour', sTeam: 'Toute l’équipe', sCustom: 'Écrire votre propre compétence',
  sInstr: 'Les étapes que l’employé doit suivre', sOn: 'Active', sOff: 'Inactive', sRemove: 'Retirer', sEmpty: 'Aucune compétence installée.', sDone: 'Installée.',
  wEyebrow: 'Workflows', wTitle: 'Workflows',
  wSub: 'Une chaîne d’étapes, chacune faite par un employé IA ; chaque étape reçoit le résultat précédent. Tourne sur le serveur, même app fermée.',
  wNew: 'Nouveau workflow', wEdit: 'Modifier', wName: 'Nom', wDesc: 'À quoi il sert (facultatif)', wSteps: 'Étapes', wAddStep: 'Ajouter une étape',
  wStepPh: 'Ce que cet employé doit faire avec l’entrée', wAgent: 'Employé', wTrigger: 'Démarre', wManual: 'À la main', wSchedule: 'Selon un horaire',
  wWebhook: 'Depuis une autre app (webhook)', wHourly: 'Toutes les heures', wDaily: 'Chaque jour', wWeekly: 'Chaque semaine', wAt: 'à', wSave: 'Enregistrer', wCancel: 'Annuler',
  wRun: 'Lancer', wInput: 'Entrée pour la première étape (facultatif)', wRuns: 'Exécutions récentes', wHook: 'Créer un lien webhook',
  wHookShown: 'Copiez ce lien maintenant : il ne s’affiche qu’une fois. Quiconque l’a peut lancer le workflow.', wDelete: 'Supprimer', wActive: 'Actif',
  wEmpty: 'Aucun workflow.', wStarted: 'Lancé. Suivez les étapes dans Tâches.', wStep: 'Étape {n}', wNoSteps: 'Ajoutez au moins une étape avec un employé.',
  wNext: 'Prochaine exécution', wRunning: 'en cours', wCompleted: 'terminé', wFailed: 'échec', wSaved: 'Enregistré.',
  fGood: 'Bon rapport', fBad: 'Pas bon', fNote: 'Qu’est-ce qui doit s’améliorer ? (facultatif)', fSend: 'Envoyer', fThanks: 'Merci. L’employé apprend de cela.',
  cTitle: 'Chat bidirectionnel avec votre CEO', cOn: 'Activer', cOff: 'Désactiver', cIsOn: 'Actif',
  cHelp: 'Ce que vous écrivez ici va à votre CEO, qui répond dans la même conversation. Les validations arrivent avec des boutons Approuver / Refuser.',
  cAppSecret: 'App secret (réglages de l’app Meta)', cCallback: 'URL de rappel', cVerify: 'Jeton de vérification',
  cMetaHelp: 'Dans votre app Meta, indiquez cette URL de rappel et ce jeton pour les webhooks WhatsApp.',
};

const zh: Copy = {
  kEyebrow: '知识库', kTitle: '公司知识库',
  kSub: '你的 AI 团队在回答前会阅读的文档、链接和应用。只有你的公司可以看到。',
  kAddText: '添加笔记或文档', kName: '名称', kText: '粘贴文本：价格、政策、产品信息、常见问题…',
  kFile: '或上传文件（.txt、.md、.csv、.json）', kAddUrl: '添加网页', kApp: '读取已连接的应用',
  kAppNone: '请先在集成中连接 Notion、GitHub、Google 云端硬盘、Gmail、Google 日历或 Outlook。',
  kAdd: '添加', kSources: '来源', kEmpty: '还没有添加内容。', kSync: '重新同步', kDelete: '移除', kItems: '{n} 个段落',
  kSearch: '试着提问', kSearchPh: '问一个你的文档能回答的问题', kNoHits: '没有找到结果。', kSaved: '已添加，AI 团队现在可以使用。',
  kErr: '操作失败，请重试。', kLimit: '已达到你的套餐的知识来源上限。', kBadUrl: '请填写完整的 https:// 链接。',
  kTooShort: '文本太短。', kManagersOnly: '只有所有者、管理员和经理可以添加或移除知识。',
  sEyebrow: '技能', sTitle: '技能库',
  sSub: '当任务匹配时 AI 员工遵循的工作方式。可为整个团队或单个员工安装。',
  sLibrary: '技能库', sInstalled: '已安装', sInstall: '安装', sFor: '用于', sTeam: '整个团队', sCustom: '编写自己的技能',
  sInstr: '员工应遵循的步骤', sOn: '开启', sOff: '关闭', sRemove: '移除', sEmpty: '还没有安装技能。', sDone: '已安装。',
  wEyebrow: '工作流', wTitle: '工作流',
  wSub: '一系列步骤，每步由一名 AI 员工完成，并接收上一步的结果。在服务器上运行，即使关闭应用也会继续。',
  wNew: '新建工作流', wEdit: '编辑', wName: '名称', wDesc: '用途（可选）', wSteps: '步骤', wAddStep: '添加步骤',
  wStepPh: '该员工应如何处理输入', wAgent: '员工', wTrigger: '启动方式', wManual: '手动', wSchedule: '定时',
  wWebhook: '来自其他应用（webhook）', wHourly: '每小时', wDaily: '每天', wWeekly: '每周', wAt: '时间', wSave: '保存', wCancel: '取消',
  wRun: '立即运行', wInput: '第一步的输入（可选）', wRuns: '最近运行', wHook: '创建 webhook 链接',
  wHookShown: '请立即复制此链接：它只显示一次。任何拥有链接的人都能启动该工作流。', wDelete: '删除', wActive: '启用',
  wEmpty: '还没有工作流。', wStarted: '已启动。在任务中查看各步骤。', wStep: '第 {n} 步', wNoSteps: '请至少添加一个带员工的步骤。',
  wNext: '下次运行', wRunning: '运行中', wCompleted: '已完成', wFailed: '失败', wSaved: '已保存。',
  fGood: '报告很好', fBad: '不够好', fNote: '哪里需要改进？（可选）', fSend: '发送', fThanks: '谢谢，员工会从中学习。',
  cTitle: '与 CEO 双向聊天', cOn: '开启', cOff: '关闭', cIsOn: '已开启',
  cHelp: '你在这里发送的消息会交给你的 CEO，CEO 会在同一聊天中回复。审批会带有批准 / 拒绝按钮。',
  cAppSecret: 'App secret（Meta 应用设置）', cCallback: '回调 URL', cVerify: '验证令牌',
  cMetaHelp: '在你的 Meta 应用中，为 WhatsApp webhook 设置此回调 URL 和验证令牌。',
};

const ar: Copy = {
  kEyebrow: 'المعرفة', kTitle: 'معرفة الشركة',
  kSub: 'مستندات وروابط وتطبيقات يقرؤها فريق الذكاء الاصطناعي قبل أن يجيب. لا يراها إلا شركتك.',
  kAddText: 'إضافة ملاحظة أو مستند', kName: 'الاسم', kText: 'الصق النص: الأسعار، السياسات، المنتجات، الأسئلة الشائعة…',
  kFile: 'أو ارفع ملفًا (.txt، .md، .csv، .json)', kAddUrl: 'إضافة صفحة ويب', kApp: 'قراءة تطبيق متصل',
  kAppNone: 'اربط أولاً Notion أو GitHub أو Google Drive أو Gmail أو تقويم Google أو Outlook من صفحة التكاملات.',
  kAdd: 'إضافة', kSources: 'المصادر', kEmpty: 'لم تتم إضافة شيء بعد.', kSync: 'مزامنة مجددًا', kDelete: 'إزالة', kItems: '{n} مقاطع',
  kSearch: 'جرّب سؤالاً', kSearchPh: 'اسأل شيئًا تجيب عنه مستنداتك', kNoHits: 'لم يُعثر على شيء.', kSaved: 'تمت الإضافة. يمكن لفريقك استخدامها الآن.',
  kErr: 'لم ينجح ذلك. حاول مرة أخرى.', kLimit: 'تم بلوغ حد مصادر المعرفة في خطتك.', kBadUrl: 'أدخل رابط https:// كاملاً.',
  kTooShort: 'النص قصير جدًا.', kManagersOnly: 'لا يضيف المعرفة أو يزيلها إلا المالكون والمسؤولون والمديرون.',
  sEyebrow: 'المهارات', sTitle: 'مكتبة المهارات',
  sSub: 'طرق عمل يتبعها موظفو الذكاء الاصطناعي عندما تناسب المهمة. ثبّتها للفريق كله أو لموظف واحد.',
  sLibrary: 'المكتبة', sInstalled: 'المثبتة', sInstall: 'تثبيت', sFor: 'لـ', sTeam: 'الفريق كله', sCustom: 'اكتب مهارتك الخاصة',
  sInstr: 'الخطوات التي يتبعها الموظف', sOn: 'مفعّلة', sOff: 'متوقفة', sRemove: 'إزالة', sEmpty: 'لا توجد مهارات مثبتة بعد.', sDone: 'تم التثبيت.',
  wEyebrow: 'سير العمل', wTitle: 'سير العمل',
  wSub: 'سلسلة خطوات، ينفذ كل خطوة موظف ذكاء اصطناعي ويتلقى نتيجة الخطوة السابقة. تعمل على الخادم حتى مع إغلاق التطبيق.',
  wNew: 'سير عمل جديد', wEdit: 'تعديل', wName: 'الاسم', wDesc: 'الغرض (اختياري)', wSteps: 'الخطوات', wAddStep: 'إضافة خطوة',
  wStepPh: 'ما الذي يفعله هذا الموظف بالمدخلات', wAgent: 'الموظف', wTrigger: 'يبدأ', wManual: 'يدويًا', wSchedule: 'حسب جدول',
  wWebhook: 'من تطبيق آخر (webhook)', wHourly: 'كل ساعة', wDaily: 'كل يوم', wWeekly: 'كل أسبوع', wAt: 'الساعة', wSave: 'حفظ', wCancel: 'إلغاء',
  wRun: 'تشغيل الآن', wInput: 'مدخلات الخطوة الأولى (اختياري)', wRuns: 'التشغيلات الأخيرة', wHook: 'إنشاء رابط webhook',
  wHookShown: 'انسخ الرابط الآن: يظهر مرة واحدة فقط. أي شخص يملكه يمكنه تشغيل سير العمل.', wDelete: 'حذف', wActive: 'مفعّل',
  wEmpty: 'لا يوجد سير عمل بعد.', wStarted: 'بدأ. تابع الخطوات في المهام.', wStep: 'الخطوة {n}', wNoSteps: 'أضف خطوة واحدة على الأقل مع موظف.',
  wNext: 'التشغيل التالي', wRunning: 'قيد التشغيل', wCompleted: 'اكتمل', wFailed: 'فشل', wSaved: 'تم الحفظ.',
  fGood: 'تقرير جيد', fBad: 'ليس جيدًا', fNote: 'ما الذي يجب تحسينه؟ (اختياري)', fSend: 'إرسال', fThanks: 'شكرًا. يتعلم الموظف من ذلك.',
  cTitle: 'دردشة ثنائية الاتجاه مع الرئيس التنفيذي', cOn: 'تشغيل', cOff: 'إيقاف', cIsOn: 'مفعّلة',
  cHelp: 'ما تكتبه هنا يصل إلى الرئيس التنفيذي الذي يرد في المحادثة نفسها. تصل الموافقات مع زري موافقة / رفض.',
  cAppSecret: 'App secret (إعدادات تطبيق Meta)', cCallback: 'رابط الاستدعاء', cVerify: 'رمز التحقق',
  cMetaHelp: 'في تطبيق Meta، اضبط رابط الاستدعاء ورمز التحقق هذين لـ webhooks واتساب.',
};

const COPY: Record<string, Copy> = { en, el, es, 'pt-BR': ptBR, de, fr, 'zh-CN': zh, ar };

/** The page text in the user's language, with {n}-style values filled in. */
export function useWorkspaceCopy() {
  const { lang } = useI18n();
  const c = COPY[lang] ?? en;
  return (key: keyof Copy, vars: Record<string, string | number> = {}) => c[key].replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ''));
}
export type WorkspaceKey = keyof Copy;
export const WORKSPACE_COPY = COPY;
