import type { Lang } from '../../i18n/core';
// Native control-plane labels stay type-checked in all eight existing languages.
const en = {
  title: 'Firbo AI engine', intro: 'Manage the shared model gateway with your Firbo account. No second login.',
  loading: 'Checking the engine…', unavailable: 'The native control API is unavailable or has not been deployed yet.',
  retry: 'Refresh', providers: 'Connected providers', models: 'Model catalogue', routes: 'Routing profiles',
  readonly: 'Changes are locked until the server rollout and verification are complete.',
  save: 'Save routing', saved: 'The gateway change was read back and verified.',
  conflict: 'The routing profile changed, or uses advanced settings. Refresh and review before editing.',
  failed: 'The change was not confirmed. Refresh before retrying.',
  modelHint: 'One exact model ID per line. The order is the fallback priority.',
  connected: 'Gateway reachable', disconnected: 'Gateway unavailable', active: 'Active', inactive: 'Inactive',
  companies: 'Your companies', role: 'Role', workspace: 'Company AI engine',
  managed: 'Gateway administration belongs to platform administrators. Agents and company data stay in Firbo.',
  back: 'Back to administration', noCompanies: 'No company membership found.', search: 'Search models',
  partial: 'Some gateway information could not be verified.', empty: 'No records returned.',
};
type Labels = { [K in keyof typeof en]: string };
export const controlLabels: Record<Lang, Labels> = {
  en,
  el: {
    title: 'Μηχανή Firbo AI', intro: 'Διαχειρίσου την κοινή πύλη μοντέλων με τον λογαριασμό Firbo, χωρίς δεύτερο login.',
    loading: 'Έλεγχος μηχανής…', unavailable: 'Το νέο API διαχείρισης δεν είναι διαθέσιμο ή δεν έχει εγκατασταθεί ακόμη.',
    retry: 'Ανανέωση', providers: 'Συνδεδεμένοι πάροχοι', models: 'Κατάλογος μοντέλων', routes: 'Προφίλ δρομολόγησης',
    readonly: 'Οι αλλαγές παραμένουν κλειδωμένες μέχρι να ολοκληρωθούν η εγκατάσταση και οι έλεγχοι του server.',
    save: 'Αποθήκευση δρομολόγησης', saved: 'Η αλλαγή διαβάστηκε ξανά από την πύλη και επιβεβαιώθηκε.',
    conflict: 'Το προφίλ άλλαξε ή χρησιμοποιεί σύνθετες ρυθμίσεις. Κάνε ανανέωση και έλεγχο πριν την αλλαγή.',
    failed: 'Η αλλαγή δεν επιβεβαιώθηκε. Κάνε ανανέωση πριν ξαναδοκιμάσεις.',
    modelHint: 'Ένα ακριβές ID μοντέλου ανά γραμμή. Η σειρά ορίζει την προτεραιότητα εναλλακτικών.',
    connected: 'Η πύλη ανταποκρίνεται', disconnected: 'Η πύλη δεν είναι διαθέσιμη', active: 'Ενεργός', inactive: 'Ανενεργός',
    companies: 'Οι εταιρείες σου', role: 'Ρόλος', workspace: 'Μηχανή AI εταιρείας',
    managed: 'Την πύλη διαχειρίζονται οι διαχειριστές πλατφόρμας. Οι agents και τα εταιρικά δεδομένα παραμένουν στο Firbo.',
    back: 'Επιστροφή στη διαχείριση', noCompanies: 'Δεν βρέθηκε συμμετοχή σε εταιρεία.', search: 'Αναζήτηση μοντέλων',
    partial: 'Ορισμένα στοιχεία της πύλης δεν επιβεβαιώθηκαν.', empty: 'Δεν επιστράφηκαν εγγραφές.',
  },
  es: {
    title: 'Motor Firbo AI', intro: 'Gestiona la pasarela compartida con tu cuenta Firbo, sin otro inicio de sesión.',
    loading: 'Comprobando el motor…', unavailable: 'La API nativa de control no está disponible o aún no se ha desplegado.',
    retry: 'Actualizar', providers: 'Proveedores conectados', models: 'Catálogo de modelos', routes: 'Perfiles de enrutamiento',
    readonly: 'Los cambios están bloqueados hasta completar el despliegue y la verificación del servidor.',
    save: 'Guardar enrutamiento', saved: 'El cambio se volvió a leer en la pasarela y se verificó.',
    conflict: 'El perfil cambió o utiliza ajustes avanzados. Actualiza y revisa antes de editar.',
    failed: 'El cambio no se confirmó. Actualiza antes de reintentar.',
    modelHint: 'Un ID exacto de modelo por línea. El orden define la prioridad de alternativas.',
    connected: 'Pasarela accesible', disconnected: 'Pasarela no disponible', active: 'Activo', inactive: 'Inactivo',
    companies: 'Tus empresas', role: 'Rol', workspace: 'Motor de IA de la empresa',
    managed: 'La pasarela la gestionan los administradores de la plataforma. Los agentes y datos de empresa permanecen en Firbo.',
    back: 'Volver a administración', noCompanies: 'No se encontró pertenencia a una empresa.', search: 'Buscar modelos',
    partial: 'No se pudo verificar parte de la información de la pasarela.', empty: 'No se devolvieron registros.',
  },
  'pt-BR': {
    title: 'Motor Firbo AI', intro: 'Gerencie o gateway compartilhado com sua conta Firbo, sem outro login.',
    loading: 'Verificando o motor…', unavailable: 'A API nativa de controle está indisponível ou ainda não foi implantada.',
    retry: 'Atualizar', providers: 'Provedores conectados', models: 'Catálogo de modelos', routes: 'Perfis de roteamento',
    readonly: 'As alterações estão bloqueadas até a implantação e verificação do servidor.',
    save: 'Salvar roteamento', saved: 'A alteração foi relida no gateway e verificada.',
    conflict: 'O perfil mudou ou usa configurações avançadas. Atualize e revise antes de editar.',
    failed: 'A alteração não foi confirmada. Atualize antes de tentar novamente.',
    modelHint: 'Um ID exato de modelo por linha. A ordem define a prioridade das alternativas.',
    connected: 'Gateway acessível', disconnected: 'Gateway indisponível', active: 'Ativo', inactive: 'Inativo',
    companies: 'Suas empresas', role: 'Função', workspace: 'Motor de IA da empresa',
    managed: 'O gateway é gerenciado pelos administradores da plataforma. Os agentes e dados da empresa ficam no Firbo.',
    back: 'Voltar à administração', noCompanies: 'Nenhum vínculo com empresa encontrado.', search: 'Buscar modelos',
    partial: 'Algumas informações do gateway não puderam ser verificadas.', empty: 'Nenhum registro retornado.',
  },
  de: {
    title: 'Firbo-AI-Engine', intro: 'Verwalte das gemeinsame Modell-Gateway mit deinem Firbo-Konto, ohne zweite Anmeldung.',
    loading: 'Engine wird geprüft…', unavailable: 'Die native Verwaltungs-API ist nicht verfügbar oder noch nicht bereitgestellt.',
    retry: 'Aktualisieren', providers: 'Verbundene Anbieter', models: 'Modellkatalog', routes: 'Routingprofile',
    readonly: 'Änderungen bleiben bis zur Bereitstellung und Prüfung des Servers gesperrt.',
    save: 'Routing speichern', saved: 'Die Änderung wurde vom Gateway zurückgelesen und bestätigt.',
    conflict: 'Das Profil wurde geändert oder nutzt erweiterte Einstellungen. Vor der Bearbeitung aktualisieren und prüfen.',
    failed: 'Die Änderung wurde nicht bestätigt. Vor einem erneuten Versuch aktualisieren.',
    modelHint: 'Eine genaue Modell-ID pro Zeile. Die Reihenfolge bestimmt die Priorität der Alternativen.',
    connected: 'Gateway erreichbar', disconnected: 'Gateway nicht verfügbar', active: 'Aktiv', inactive: 'Inaktiv',
    companies: 'Deine Unternehmen', role: 'Rolle', workspace: 'Unternehmens-KI-Engine',
    managed: 'Das Gateway wird von Plattformadministratoren verwaltet. Agenten und Unternehmensdaten bleiben in Firbo.',
    back: 'Zurück zur Verwaltung', noCompanies: 'Keine Unternehmensmitgliedschaft gefunden.', search: 'Modelle suchen',
    partial: 'Einige Gateway-Informationen konnten nicht bestätigt werden.', empty: 'Keine Einträge zurückgegeben.',
  },
  fr: {
    title: 'Moteur Firbo AI', intro: 'Gérez la passerelle partagée avec votre compte Firbo, sans seconde connexion.',
    loading: 'Vérification du moteur…', unavailable: 'L’API native de gestion est indisponible ou pas encore déployée.',
    retry: 'Actualiser', providers: 'Fournisseurs connectés', models: 'Catalogue des modèles', routes: 'Profils de routage',
    readonly: 'Les modifications restent verrouillées jusqu’au déploiement et à la vérification du serveur.',
    save: 'Enregistrer le routage', saved: 'La modification a été relue sur la passerelle et vérifiée.',
    conflict: 'Le profil a changé ou utilise des réglages avancés. Actualisez et vérifiez avant de modifier.',
    failed: 'La modification n’a pas été confirmée. Actualisez avant de réessayer.',
    modelHint: 'Un identifiant exact de modèle par ligne. L’ordre définit la priorité des alternatives.',
    connected: 'Passerelle accessible', disconnected: 'Passerelle indisponible', active: 'Actif', inactive: 'Inactif',
    companies: 'Vos entreprises', role: 'Rôle', workspace: 'Moteur IA de l’entreprise',
    managed: 'La passerelle est gérée par les administrateurs de la plateforme. Les agents et données restent dans Firbo.',
    back: 'Retour à l’administration', noCompanies: 'Aucune appartenance à une entreprise trouvée.', search: 'Rechercher des modèles',
    partial: 'Certaines informations de la passerelle n’ont pas pu être vérifiées.', empty: 'Aucun enregistrement renvoyé.',
  },
  'zh-CN': {
    title: 'Firbo AI 引擎', intro: '使用 Firbo 账户管理共享模型网关，无需再次登录。',
    loading: '正在检查引擎…', unavailable: '原生管理 API 不可用或尚未部署。',
    retry: '刷新', providers: '已连接的提供商', models: '模型目录', routes: '路由配置',
    readonly: '服务器部署和验证完成前，修改保持锁定。',
    save: '保存路由', saved: '已从网关重新读取并验证修改。',
    conflict: '配置已更改或使用了高级设置。编辑前请刷新并检查。',
    failed: '修改尚未确认。重试前请刷新。',
    modelHint: '每行输入一个完整的模型 ID，顺序决定备选优先级。',
    connected: '网关可访问', disconnected: '网关不可用', active: '启用', inactive: '停用',
    companies: '你的公司', role: '角色', workspace: '公司 AI 引擎',
    managed: '网关由平台管理员管理。智能体和公司数据保留在 Firbo 中。',
    back: '返回管理', noCompanies: '未找到公司成员关系。', search: '搜索模型',
    partial: '部分网关信息无法验证。', empty: '未返回记录。',
  },
  ar: {
    title: 'محرك Firbo AI', intro: 'أدر البوابة المشتركة بحساب Firbo دون تسجيل دخول ثانٍ.',
    loading: 'جارٍ فحص المحرك…', unavailable: 'واجهة الإدارة الأصلية غير متاحة أو لم تُنشر بعد.',
    retry: 'تحديث', providers: 'المزوّدون المتصلون', models: 'دليل النماذج', routes: 'ملفات التوجيه',
    readonly: 'تبقى التغييرات مقفلة حتى اكتمال نشر الخادم والتحقق منه.',
    save: 'حفظ التوجيه', saved: 'أُعيدت قراءة التغيير من البوابة وتم التحقق منه.',
    conflict: 'تغيّر الملف أو يستخدم إعدادات متقدمة. حدّث وراجع قبل التعديل.',
    failed: 'لم يتم تأكيد التغيير. حدّث قبل المحاولة مجدداً.',
    modelHint: 'معرّف نموذج كامل في كل سطر. يحدد الترتيب أولوية البدائل.',
    connected: 'البوابة متاحة', disconnected: 'البوابة غير متاحة', active: 'نشط', inactive: 'غير نشط',
    companies: 'شركاتك', role: 'الدور', workspace: 'محرك الذكاء الاصطناعي للشركة',
    managed: 'يدير مسؤولو المنصة البوابة. تبقى الوكلاء وبيانات الشركة في Firbo.',
    back: 'العودة إلى الإدارة', noCompanies: 'لم يتم العثور على عضوية في شركة.', search: 'البحث عن نماذج',
    partial: 'تعذّر التحقق من بعض معلومات البوابة.', empty: 'لم تُرجع أي سجلات.',
  },
};
