import test from 'node:test';
import assert from 'node:assert/strict';
import { createSpeechHandler } from '../../../supabase/functions/agent-speak/handler.ts';
import { DARK_PROFILE, NATURAL_PROFILE, DARK_RATE, MAX_PCM_BYTES, SAMPLE_RATE, profileOf, renderWave, speechRequest } from '../../../supabase/functions/agent-speak/audio-profile.ts';
import { speechAudioBlob } from '../../../frontend/src/lib/company/speechAudio.ts';
import { defaultVoiceProfile, getVoiceProfile, setVoiceProfile } from '../../../frontend/src/lib/company/voiceProfile.ts';
const pcm = (hz=200, seconds=1, amplitude=0.4) => {
  const b = new Uint8Array(Math.floor(SAMPLE_RATE*seconds)*2), v = new DataView(b.buffer);
  for(let i=0;i<b.length/2;i++) v.setInt16(i*2,Math.round(32767*amplitude*Math.sin(2*Math.PI*hz*i/SAMPLE_RATE)),true);
  return b;
};
const mp3 = new Uint8Array([73,68,51,4,0,0,0,0,0,0,255,251,144,0]);
const dataFrom = (wave) => { const v = new DataView(wave.buffer,wave.byteOffset,wave.byteLength); return Float64Array.from({length:(wave.length-44)/2},(_,i)=>v.getInt16(44+i*2,true)/32768); };
function fixture(opt={}) {
  const calls=[],saved=[],db=[];
  const env={SUPABASE_URL:'https://test.invalid',SUPABASE_ANON_KEY:'public-fixture',SUPABASE_SERVICE_ROLE_KEY:'private-fixture',OPENAI_API_KEY:'provider-fixture',...opt.env};
  const client={auth:{getUser:async()=>({data:{user:opt.noUser?null:{id:'user-1',email:'user@example.com'}},error:opt.authError})},from(table){
    const filters=[];
    const chain={select(){return chain},eq(k,v){filters.push([k,v]);return chain},gte(){return chain},maybeSingle:async()=>{db.push({table,filters});return {data:opt.foreign?null:{role:opt.role??'owner'},error:opt.memberError}},then(resolve,reject){db.push({table,filters});return Promise.resolve({count:opt.count??0,error:opt.usageError}).then(resolve,reject)},insert:async(row)=>{saved.push(row);return{error:opt.saveError}}};
    return chain;
  }};
  const http=async(url,init)=>{ const body=JSON.parse(init.body);calls.push({url,init,body});
    if(opt.http)return opt.http(body,calls.length,init);
    if(opt.status)return new Response('private_provider_diagnostic',{status:opt.status});
    return new Response(body.response_format==='pcm'?pcm():mp3,{headers:{'content-type':'application/octet-stream'}});
  };
  const handler=createSpeechHandler({createClient:()=>client,env:k=>env[k],http});
  const invoke=(extra={},headers={},method='POST')=>handler(new Request('https://test.invalid/speak',{method,headers:{authorization:'Bearer fixture','content-type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify({organization_id:'org-1',text:'Synthetic text only.',...extra})}:{})}));
  return{handler,invoke,calls,saved,db};
}
test('default profile is Dark in server and browser, not old warm voice',()=>{assert.equal(profileOf(),DARK_PROFILE);assert.equal(defaultVoiceProfile(),DARK_PROFILE);assert.equal(getVoiceProfile(),DARK_PROFILE);});
test('profile selection rejects unknown presets and custom model injection',()=>{assert.throws(()=>profileOf('clone-celebrity'));assert.throws(()=>speechRequest('user-model','x',DARK_PROFILE,true));});
test('natural remains a deliberate reversible preference',()=>{setVoiceProfile(NATURAL_PROFILE);assert.equal(getVoiceProfile(),NATURAL_PROFILE);setVoiceProfile(DARK_PROFILE);assert.equal(getVoiceProfile(),DARK_PROFILE);});
test('Dark request changes prosody; tts-1 never receives unsupported instructions',()=>{const r=speechRequest('gpt-4o-mini-tts','Γεια σου',DARK_PROFILE,true);assert.match(r.instructions,/bass-baritone/);assert.equal(r.input,'Γεια σου');assert.equal(r.response_format,'pcm');assert.equal('instructions' in speechRequest('tts-1','x',DARK_PROFILE,true),false);});
test('natural WAV preserves every PCM sample',()=>{const a=pcm(),w=renderWave(a,NATURAL_PROFILE);assert.deepEqual(w.slice(44),a);});
test('processed WAV has valid bounded length and lower pitch/time relation',()=>{const w=renderWave(pcm(),DARK_PROFILE);assert.equal(w.length,44+2*Math.ceil(SAMPLE_RATE/DARK_RATE));const v=new DataView(w.buffer);assert.equal(v.getUint32(24,true),24000);assert.equal(v.getUint32(4,true),w.length-8);});
test('Dark waveform objectively lowers a 200Hz tone to about172Hz',()=>{const y=dataFrom(renderWave(pcm(200,2),DARK_PROFILE));let crossings=0;for(let i=5000;i<y.length-5000;i++)if(y[i]<0&&y[i+1]>=0)crossings++;const hz=crossings*SAMPLE_RATE/(y.length-10000);assert.ok(Math.abs(hz-172)<2,{hz});});
test('DSP never introduces background noise into silence',()=>{const w=renderWave(new Uint8Array(48000),DARK_PROFILE);assert.ok(w.slice(44).every(x=>x===0));});
test('DSP keeps high amplitude finite, bounded, with silent endpoints',()=>{const y=dataFrom(renderWave(pcm(120,1,1),DARK_PROFILE));assert.ok(y.every(x=>Number.isFinite(x)&&Math.abs(x)<=.901));assert.equal(y[0],0);assert.equal(y.at(-1),0);});
test('DSP is deterministic',()=>assert.deepEqual(renderWave(pcm(),DARK_PROFILE),renderWave(pcm(),DARK_PROFILE)));
for(const [name,bytes] of [['empty',new Uint8Array()],['odd',new Uint8Array(3)],['oversize',new Uint8Array(MAX_PCM_BYTES+2)],['json',new TextEncoder().encode('{"error":1234}')],['mp3',mp3]])test(`DSP refuses ${name}`,()=>assert.throws(()=>renderWave(bytes,DARK_PROFILE)));
test('WAV survives actual server-octet-stream to browser-Blob normalization',async()=>{const original=renderWave(pcm(),DARK_PROFILE);const blob=await speechAudioBlob(new Blob([original],{type:'application/octet-stream'}),true);assert.equal(blob.type,'audio/wav');assert.deepEqual(new Uint8Array(await blob.arrayBuffer()),original);});
test('old MP3 cannot masquerade as Dark, but remains valid Natural response',async()=>{const b=new Blob([mp3],{type:'application/octet-stream'});await assert.rejects(speechAudioBlob(b,true),/dark_voice_not_available/);assert.equal((await speechAudioBlob(b,false)).type,'audio/mpeg');});
test('WAV declared length mismatch is rejected',async()=>{const w=renderWave(pcm(),DARK_PROFILE);w[40]=0;await assert.rejects(speechAudioBlob(new Blob([w],{type:'application/octet-stream'}),true));});
test('JSON HTML empty and oversized envelopes are never speech',async()=>{for(const b of [new Blob(['<html/>'],{type:'text/html'}),new Blob(['{}'],{type:'application/json'}),new Blob(),new Blob([new Uint8Array(8000001)])])await assert.rejects(speechAudioBlob(b,true));});
test('old clients remain MP3-compatible but get dark prompt and slower speed',async()=>{const f=fixture();const r=await f.invoke();assert.equal(r.status,200);assert.equal(r.headers.get('x-firbo-audio-format'),'mp3');assert.equal(f.calls[0].body.speed,.88);assert.match(f.calls[0].body.instructions,/deep, resonant/);assert.deepEqual(new Uint8Array(await r.arrayBuffer()),mp3);});
test('new clients receive real processedWAV, not unchanged bytes',async()=>{const f=fixture();const r=await f.invoke({voice_profile:DARK_PROFILE,audio_format:'wav'});assert.equal(r.status,200);assert.equal(r.headers.get('x-firbo-voice-profile'),DARK_PROFILE);const bytes=new Uint8Array(await r.arrayBuffer());assert.deepEqual(bytes,renderWave(pcm(),DARK_PROFILE));assert.equal(f.saved.length,1);assert.equal(f.saved[0].organization_id,'org-1');});
test('server Natural emits unmodified audio',async()=>{const f=fixture();const r=await f.invoke({voice_profile:NATURAL_PROFILE});assert.equal(r.status,200);assert.equal(f.calls[0].body.speed,1);assert.match(f.calls[0].body.instructions,/natural phrasing/);});
for(const [name,opt,status] of [['no login',{noUser:true},401],['auth error',{authError:{}},401],['viewer',{role:'viewer'},403],['other company',{foreign:true},403],['membership unavailable',{memberError:{}},503],['email restriction',{env:{RUN_ALLOWED_EMAILS:'other@example.com'}},403],['no provider key',{env:{OPENAI_API_KEY:''}},503],['quota',{count:300},429],['counter unavailable',{usageError:{}},503],['bad cap',{env:{ORG_DAILY_RUN_LIMIT:'NaN'}},503]])test(`guard ${name} prevents generation`,async()=>{const f=fixture(opt),r=await f.invoke();assert.equal(r.status,status);assert.equal(f.calls.length,0);});
for(const [name,body,status] of [['empty text',{text:''},400],['overlong',{text:'x'.repeat(701)},413],['invalid preset',{voice_profile:'other'},400],['unsupported codec',{audio_format:'exe'},400],['huge body',{text:'x'.repeat(17000)},400]])test(`request ${name} is denied before provider call`,async()=>{const f=fixture(),r=await f.invoke(body);assert.equal(r.status,status);assert.equal(f.calls.length,0);});
test('missing authorization cannot call SDK/provider',async()=>{const f=fixture();const r=await f.handler(new Request('https://test.invalid/speak',{method:'POST',body:'{}'}));assert.equal(r.status,401);assert.equal(f.calls.length,0);});
test('OPTIONS and unsupported methods are nonbillable',async()=>{const f=fixture();assert.equal((await f.invoke({}, {},'OPTIONS')).status,200);assert.equal((await f.invoke({}, {},'GET')).status,405);assert.equal(f.calls.length,0);});
for(const status of [401,402,403,429,500])test(`provider ${status} does not silently switch model`,async()=>{const f=fixture({status});const r=await f.invoke({audio_format:'wav'});assert.notEqual(r.status,200);assert.equal(f.calls.length,1);assert.ok(!(await r.text()).includes('private_provider'));});
test('only definite model rejection permits fallback and same DSP applies',async()=>{const f=fixture({http:(body,n)=>n===1?new Response('',{status:404}):new Response(pcm(),{headers:{'content-type':'audio/pcm'}})});const r=await f.invoke({audio_format:'wav'});assert.equal(r.status,200);assert.equal(f.calls[1].body.model,'tts-1');assert.deepEqual(new Uint8Array(await r.arrayBuffer()),renderWave(pcm(),DARK_PROFILE));});
test('network uncertainty cannot trigger a second potentially billed synthesis',async()=>{const f=fixture({http:()=>{throw new Error('network')}});assert.equal((await f.invoke()).status,502);assert.equal(f.calls.length,1);});
test('usage write failure is explicit and never reruns speech',async()=>{const f=fixture({saveError:{}});assert.equal((await f.invoke()).status,503);assert.equal(f.calls.length,1);});
test('actual org/user filters are applied to authority lookup',async()=>{const f=fixture();await f.invoke();assert.deepEqual(f.db[0].filters,[['organization_id','org-1'],['user_id','user-1']]);});
test('successful sound is no-store and cannot contain provider credentials',async()=>{const f=fixture();const r=await f.invoke({audio_format:'wav'});assert.match(r.headers.get('cache-control'),/no-store/);assert.ok(!JSON.stringify([...r.headers]).includes('provider-fixture'));assert.equal(f.calls[0].init.redirect,'error');});
test('provider body is size-bounded and cannot return HTML as a voice',async()=>{const f=fixture({http:()=>new Response('<html/>',{headers:{'content-type':'text/html'}})});assert.equal((await f.invoke({audio_format:'wav'})).status,502);assert.equal(f.saved.length,0);});
